--  The v3x2 CRC32C geometry and constants were generated by
--  corsix/fast-crc32 with
--  `./generate -i avx512_vpclmulqdq -p crc32c -a v3x2` and then altered and
--  translated to Ada. See THIRD_PARTY_NOTICES.md.

with System.Machine_Code;
with System.Storage_Elements;

package body Flyology_CRC.CRC32C_X86_AVX512_VPCLMUL_V3X2 is
   use System.Machine_Code;
   use type System.Bit_Order;
   use type System.Storage_Elements.Storage_Count;

   subtype U8 is Interfaces.Unsigned_8;
   subtype U32 is Interfaces.Unsigned_32;
   subtype U64 is Interfaces.Unsigned_64;
   subtype Count is System.Storage_Elements.Storage_Count;

   type Vector_512 is array (Natural range 0 .. 7) of U64 with Alignment => 64;
   pragma Machine_Attribute (Vector_512, "vector_type");

   --  These private constants are the exact polynomial folding constants in
   --  the pinned oracle.  Keeping their addressable representation in rodata
   --  lets the assembly leaf load them once, outside the repeated block loop.
   K_Fold_384_Low  : aliased constant U64 := 16#0000_0000_A87A_B8A8#;
   K_Fold_384_High : aliased constant U64 := 16#0000_0000_AB7A_FF2A#;

   K_Reduce_3_To_1_Low  : aliased constant U64 := 16#0000_0000_740E_EF02#;
   K_Reduce_3_To_1_High : aliased constant U64 := 16#0000_0000_9E4A_DDF8#;

   K_Reduce_512_To_128 : aliased constant Vector_512 :=
     (16#0000_0000_1C29_1D04#, 16#0000_0000_DDC0_152B#,
      16#0000_0000_3DA6_D0CB#, 16#0000_0000_BA4F_C28E#,
      16#0000_0000_F20C_0DFE#, 16#0000_0000_493C_7D27#,
      0, 0);

   pragma Compile_Time_Error
     (System.Default_Bit_Order /= System.Low_Order_First,
      "the x86-64 CRC32C AVX-512 VPCLMUL kernel requires little-endian byte order");
   pragma Compile_Time_Error
     (System.Word_Size /= 64,
      "the x86-64 CRC32C AVX-512 VPCLMUL kernel requires 64-bit words");

   function Next
     (Source : System.Address;
      Bytes  : Count) return System.Address is
     (System.Storage_Elements."+"
        (Source, System.Storage_Elements.Storage_Offset (Bytes)));
   pragma Inline_Always (Next);

   function Alignment
     (Source : System.Address;
      Bytes  : Count) return Count is
     (Count
        (System.Storage_Elements."mod"
           (Source, System.Storage_Elements.Storage_Offset (Bytes))));
   pragma Inline_Always (Alignment);

   function CRC32C_Byte (CRC : U32; Source : System.Address) return U32 is
      Item   : U8 with Import, Address => Source;
      Result : U32 := CRC;
   begin
      Asm
        (Template => "crc32b %b1, %0",
         Outputs  => U32'Asm_Output ("+r", Result),
         Inputs   => U8'Asm_Input ("m", Item));
      return Result;
   end CRC32C_Byte;
   pragma Inline_Always (CRC32C_Byte);

   function CRC32C_64 (CRC : U32; Source : System.Address) return U32 is
      Item   : U64 with Import, Address => Source;
      Result : U32 := CRC;
   begin
      Asm
        (Template => "crc32q %1, %q0",
         Outputs  => U32'Asm_Output ("+r", Result),
         Inputs   => U64'Asm_Input ("m", Item));
      return Result;
   end CRC32C_64;
   pragma Inline_Always (CRC32C_64);

   procedure CRC32C_64_Byte_Block
     (CRC     : in out U32;
      Pointer : in out System.Address) is
   begin
      --  Match the pinned oracle's eight-way scalar tail.  Keeping all eight
      --  loads in one leaf removes the per-word Ada loop branch without
      --  staging or copying any payload bytes.
      Asm
        (Template =>
           "crc32q 0(%1), %q0" & ASCII.LF & ASCII.HT &
           "crc32q 8(%1), %q0" & ASCII.LF & ASCII.HT &
           "crc32q 16(%1), %q0" & ASCII.LF & ASCII.HT &
           "crc32q 24(%1), %q0" & ASCII.LF & ASCII.HT &
           "crc32q 32(%1), %q0" & ASCII.LF & ASCII.HT &
           "crc32q 40(%1), %q0" & ASCII.LF & ASCII.HT &
           "crc32q 48(%1), %q0" & ASCII.LF & ASCII.HT &
           "crc32q 56(%1), %q0" & ASCII.LF & ASCII.HT &
           "addq $64, %1",
         Outputs =>
           [U32'Asm_Output ("+&r", CRC),
            System.Address'Asm_Output ("+&r", Pointer)],
         Clobber  => "cc,memory",
         Volatile => True);
   end CRC32C_64_Byte_Block;
   pragma Inline_Always (CRC32C_64_Byte_Block);

   procedure Fold_384_Blocks
     (Pointer : in out System.Address;
      Blocks  : in out Count;
      CRC     : in out U32) is
   begin
      --  ZMM0..2 are the three independent 512-bit streams.  Each steady
      --  iteration performs two complete folds, consuming 384 bytes.  The
      --  final stream and lane reductions stay in registers and feed the two
      --  CRC32Q instructions directly; no payload is staged or copied.
      Asm
        (Template =>
           "vmovdqu64 64(%0), %%zmm0" & ASCII.LF & ASCII.HT &
           "vmovdqu64 128(%0), %%zmm5" & ASCII.LF & ASCII.HT &
           "vmovd %k2, %%xmm1" & ASCII.LF & ASCII.HT &
           "vpxorq 0(%0), %%zmm1, %%zmm1" & ASCII.LF & ASCII.HT &
           "vpbroadcastq 0(%3), %%zmm3" & ASCII.LF & ASCII.HT &
           "vpbroadcastq 0(%4), %%zmm4" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $0, %%zmm3, %%zmm1, %%zmm6" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $17, %%zmm4, %%zmm1, %%zmm1" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $0, %%zmm3, %%zmm0, %%zmm7" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $17, %%zmm4, %%zmm0, %%zmm2" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $0, %%zmm3, %%zmm5, %%zmm8" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $17, %%zmm4, %%zmm5, %%zmm0" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, 192(%0), %%zmm6, %%zmm1" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, 256(%0), %%zmm7, %%zmm2" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, 320(%0), %%zmm8, %%zmm0" & ASCII.LF & ASCII.HT &
           "addq $384, %0" & ASCII.LF & ASCII.HT &
           "decq %1" & ASCII.LF & ASCII.HT &
           "jz 2f" & ASCII.LF & ASCII.HT &
           "1:" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $0, %%zmm3, %%zmm1, %%zmm5" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $17, %%zmm4, %%zmm1, %%zmm1" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $0, %%zmm3, %%zmm2, %%zmm6" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $17, %%zmm4, %%zmm2, %%zmm2" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $0, %%zmm3, %%zmm0, %%zmm7" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $17, %%zmm4, %%zmm0, %%zmm0" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, 0(%0), %%zmm5, %%zmm1" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, 64(%0), %%zmm6, %%zmm2" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, 128(%0), %%zmm7, %%zmm0" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $0, %%zmm3, %%zmm1, %%zmm5" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $17, %%zmm4, %%zmm1, %%zmm1" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $0, %%zmm3, %%zmm2, %%zmm6" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $17, %%zmm4, %%zmm2, %%zmm2" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $0, %%zmm3, %%zmm0, %%zmm7" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $17, %%zmm4, %%zmm0, %%zmm0" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, 192(%0), %%zmm5, %%zmm1" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, 256(%0), %%zmm6, %%zmm2" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, 320(%0), %%zmm7, %%zmm0" & ASCII.LF & ASCII.HT &
           "addq $384, %0" & ASCII.LF & ASCII.HT &
           "decq %1" & ASCII.LF & ASCII.HT &
           "jnz 1b" & ASCII.LF & ASCII.HT &
           "2:" & ASCII.LF & ASCII.HT &
           "vpbroadcastq 0(%5), %%zmm3" & ASCII.LF & ASCII.HT &
           "vpbroadcastq 0(%6), %%zmm4" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $0, %%zmm3, %%zmm1, %%zmm5" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $17, %%zmm4, %%zmm1, %%zmm1" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, %%zmm2, %%zmm5, %%zmm1" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $0, %%zmm3, %%zmm1, %%zmm2" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $17, %%zmm4, %%zmm1, %%zmm1" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, %%zmm0, %%zmm2, %%zmm1" & ASCII.LF & ASCII.HT &
           "vmovdqu64 0(%7), %%zmm3" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $0, %%zmm3, %%zmm1, %%zmm4" & ASCII.LF & ASCII.HT &
           "vpclmulqdq $17, %%zmm3, %%zmm1, %%zmm3" & ASCII.LF & ASCII.HT &
           "vpxorq %%zmm3, %%zmm4, %%zmm4" & ASCII.LF & ASCII.HT &
           "vextracti32x4 $1, %%zmm4, %%xmm5" & ASCII.LF & ASCII.HT &
           "vextracti32x4 $2, %%zmm4, %%xmm6" & ASCII.LF & ASCII.HT &
           "vextracti32x4 $3, %%zmm1, %%xmm7" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, %%xmm6, %%xmm5, %%xmm4" & ASCII.LF & ASCII.HT &
           "vpxorq %%xmm7, %%xmm4, %%xmm4" & ASCII.LF & ASCII.HT &
           "vmovq %%xmm4, %%r8" & ASCII.LF & ASCII.HT &
           "vpextrq $1, %%xmm4, %%r9" & ASCII.LF & ASCII.HT &
           "xorl %k2, %k2" & ASCII.LF & ASCII.HT &
           "crc32q %%r8, %q2" & ASCII.LF & ASCII.HT &
           "crc32q %%r9, %q2",
         Outputs =>
           [System.Address'Asm_Output ("+&r", Pointer),
            Count'Asm_Output ("+&r", Blocks),
            U32'Asm_Output ("+&r", CRC)],
         Inputs =>
           [System.Address'Asm_Input ("r", K_Fold_384_Low'Address),
            System.Address'Asm_Input ("r", K_Fold_384_High'Address),
            System.Address'Asm_Input ("r", K_Reduce_3_To_1_Low'Address),
            System.Address'Asm_Input ("r", K_Reduce_3_To_1_High'Address),
            System.Address'Asm_Input ("r", K_Reduce_512_To_128'Address)],
         Clobber =>
           "cc,memory,r8,r9,zmm0,zmm1,zmm2,zmm3,zmm4,zmm5,zmm6,zmm7,zmm8",
         Volatile => True);
   end Fold_384_Blocks;
   pragma Inline_Always (Fold_384_Blocks);

   function Update
     (State : U32;
      Data  : Byte_Array) return U32 is
      CRC       : U32 := State;
      Pointer   : System.Address := Data'Address;
      Remaining : Count := Count (Data'Length);
   begin
      --  Match the pinned oracle: first align to a word with CRC32B, then to a
      --  64-byte cache line with CRC32Q before entering the ZMM path.
      while Remaining > 0 and then Alignment (Pointer, 8) /= 0 loop
         CRC := CRC32C_Byte (CRC, Pointer);
         Pointer := Next (Pointer, 1);
         Remaining := Remaining - 1;
      end loop;

      while Alignment (Pointer, 64) /= 0 and then Remaining >= 8 loop
         CRC := CRC32C_64 (CRC, Pointer);
         Pointer := Next (Pointer, 8);
         Remaining := Remaining - 8;
      end loop;

      if Remaining >= 384 then
         declare
            Blocks   : Count := Remaining / 384;
            Consumed : constant Count := Blocks * 384;
         begin
            Fold_384_Blocks (Pointer, Blocks, CRC);
            Remaining := Remaining - Consumed;
         end;
      end if;

      while Remaining >= 64 loop
         CRC32C_64_Byte_Block (CRC, Pointer);
         Remaining := Remaining - 64;
      end loop;

      while Remaining >= 8 loop
         CRC := CRC32C_64 (CRC, Pointer);
         Pointer := Next (Pointer, 8);
         Remaining := Remaining - 8;
      end loop;

      while Remaining > 0 loop
         CRC := CRC32C_Byte (CRC, Pointer);
         Pointer := Next (Pointer, 1);
         Remaining := Remaining - 1;
      end loop;
      return CRC;
   end Update;

   function Compiled return Boolean is (True);
end Flyology_CRC.CRC32C_X86_AVX512_VPCLMUL_V3X2;
