--  The v4s3x3 CRC32C geometry and constants were generated by
--  corsix/fast-crc32 with `./generate -i avx512 -p crc32c -a v4s3x3` and
--  then altered and translated to Ada. See THIRD_PARTY_NOTICES.md.

with System.Machine_Code;
with System.Storage_Elements;

package body Flyology_CRC.CRC32C_X86_AVX512_PCLMUL_V4S3X3 is
   use System.Machine_Code;
   use type Interfaces.Unsigned_32;
   use type Interfaces.Unsigned_64;
   use type System.Bit_Order;
   use type System.Storage_Elements.Storage_Count;

   subtype U8 is Interfaces.Unsigned_8;
   subtype U32 is Interfaces.Unsigned_32;
   subtype U64 is Interfaces.Unsigned_64;
   subtype Count is System.Storage_Elements.Storage_Count;

   type Vector_128 is array (0 .. 1) of U64 with Alignment => 16;
   pragma Machine_Attribute (Vector_128, "vector_type");

   type Accumulator_Array is array (Natural range 0 .. 3) of Vector_128
   with Alignment => 16;

   type Byte_Block_16 is array (Natural range 0 .. 15) of U8 with Pack;

   pragma Compile_Time_Error
     (System.Default_Bit_Order /= System.Low_Order_First,
      "the x86-64 CRC32C AVX-512 fusion kernel requires little-endian byte order");
   pragma Compile_Time_Error
     (System.Word_Size /= 64,
      "the x86-64 CRC32C AVX-512 fusion kernel requires 64-bit words");

   function Next
     (Source : System.Address;
      Bytes  : Count) return System.Address is
     (System.Storage_Elements."+"
        (Source, System.Storage_Elements.Storage_Offset (Bytes)));
   pragma Inline_Always (Next);

   function Alignment
     (Source : System.Address;
      Bytes  : Count) return Count is
     (Count
        (System.Storage_Elements."mod"
           (Source, System.Storage_Elements.Storage_Offset (Bytes))));
   pragma Inline_Always (Alignment);

   function Load_64 (Source : System.Address) return U64 is
      Item : U64 with Import, Address => Source;
   begin
      return Item;
   end Load_64;
   pragma Inline_Always (Load_64);

   function Load_128 (Source : System.Address) return Vector_128 is
      Bytes  : Byte_Block_16 with Import, Address => Source;
      Result : Vector_128;
   begin
      Asm
        (Template => "movdqu %1, %0",
         Outputs  => Vector_128'Asm_Output ("=&x", Result),
         Inputs   => Byte_Block_16'Asm_Input ("m", Bytes));
      return Result;
   end Load_128;
   pragma Inline_Always (Load_128);

   function Xor_128 (Left, Right : Vector_128) return Vector_128 is
      Result : Vector_128 := Left;
   begin
      Asm
        (Template => "pxor %1, %0",
         Outputs  => Vector_128'Asm_Output ("+x", Result),
         Inputs   => Vector_128'Asm_Input ("x", Right));
      return Result;
   end Xor_128;
   pragma Inline_Always (Xor_128);

   function Ternary_Xor_128
     (First, Second, Third : Vector_128) return Vector_128 is
      Result : Vector_128 := First;
   begin
      --  Immediate 16#96# is the architectural three-input XOR truth table.
      Asm
        (Template => "vpternlogq $0x96, %2, %1, %0",
         Outputs  => Vector_128'Asm_Output ("+v", Result),
         Inputs   =>
           [Vector_128'Asm_Input ("v", Second),
            Vector_128'Asm_Input ("vm", Third)]);
      return Result;
   end Ternary_Xor_128;
   pragma Inline_Always (Ternary_Xor_128);

   function CLMUL_Low (Left, Right : Vector_128) return Vector_128 is
      Result : Vector_128 := Left;
   begin
      Asm
        (Template => "pclmulqdq $0, %1, %0",
         Outputs  => Vector_128'Asm_Output ("+x", Result),
         Inputs   => Vector_128'Asm_Input ("x", Right));
      return Result;
   end CLMUL_Low;
   pragma Inline_Always (CLMUL_Low);

   function CLMUL_High (Left, Right : Vector_128) return Vector_128 is
      Result : Vector_128 := Left;
   begin
      Asm
        (Template => "pclmulqdq $17, %1, %0",
         Outputs  => Vector_128'Asm_Output ("+x", Result),
         Inputs   => Vector_128'Asm_Input ("x", Right));
      return Result;
   end CLMUL_High;
   pragma Inline_Always (CLMUL_High);

   function Extract_Low (Value : Vector_128) return U64 is
      Result : U64;
   begin
      Asm
        (Template => "movq %1, %0",
         Outputs  => U64'Asm_Output ("=r", Result),
         Inputs   => Vector_128'Asm_Input ("x", Value));
      return Result;
   end Extract_Low;
   pragma Inline_Always (Extract_Low);

   function Extract_High (Value : Vector_128) return U64 is
      Result : U64;
   begin
      Asm
        (Template => "pextrq $1, %1, %0",
         Outputs  => U64'Asm_Output ("=r", Result),
         Inputs   => Vector_128'Asm_Input ("x", Value));
      return Result;
   end Extract_High;
   pragma Inline_Always (Extract_High);

   function CRC32C_Byte (CRC : U32; Source : System.Address) return U32 is
      Item   : U8 with Import, Address => Source;
      Result : U32 := CRC;
   begin
      Asm
        (Template => "crc32b %1, %0",
         Outputs  => U32'Asm_Output ("+r", Result),
         Inputs   => U8'Asm_Input ("m", Item));
      return Result;
   end CRC32C_Byte;
   pragma Inline_Always (CRC32C_Byte);

   function CRC32C_32 (CRC, Item : U32) return U32 is
      Result : U32 := CRC;
   begin
      Asm
        (Template => "crc32l %1, %0",
         Outputs  => U32'Asm_Output ("+r", Result),
         Inputs   => U32'Asm_Input ("r", Item));
      return Result;
   end CRC32C_32;
   pragma Inline_Always (CRC32C_32);

   function CRC32C_64
     (CRC    : U32;
      Source : System.Address) return U32 is
      Item   : U64 with Import, Address => Source;
      Result : U32 := CRC;
   begin
      Asm
        (Template => "crc32q %1, %q0",
         Outputs  => U32'Asm_Output ("+r", Result),
         Inputs   => U64'Asm_Input ("m", Item));
      return Result;
   end CRC32C_64;
   pragma Inline_Always (CRC32C_64);

   function CRC32C_64_Value (CRC : U32; Item : U64) return U32 is
      Result : U32 := CRC;
   begin
      Asm
        (Template => "crc32q %1, %q0",
         Outputs  => U32'Asm_Output ("+r", Result),
         Inputs   => U64'Asm_Input ("r", Item));
      return Result;
   end CRC32C_64_Value;
   pragma Inline_Always (CRC32C_64_Value);

   function CLMUL_Scalar (Left, Right : U32) return Vector_128 is
     (CLMUL_Low ((U64 (Left), 0), (U64 (Right), 0)));
   pragma Inline_Always (CLMUL_Scalar);

   function XNModP (Exponent : U64) return U32 is
      N     : U64 := Exponent;
      Stack : U64 := not U64 (1);
      Acc   : U32;
      Low   : U32;
   begin
      while N > 191 loop
         Stack := Interfaces.Shift_Left (Stack, 1) + (N and 1);
         N := Interfaces.Shift_Right (N, 1) - 16;
      end loop;
      Stack := not Stack;

      Acc := Interfaces.Shift_Right (U32 (16#8000_0000#), Natural (N and 31));
      N := Interfaces.Shift_Right (N, 5);
      while N > 0 loop
         Acc := CRC32C_32 (Acc, 0);
         N := N - 1;
      end loop;

      loop
         Low := U32 (Stack and 1);
         Stack := Interfaces.Shift_Right (Stack, 1);
         exit when Stack = 0;
         declare
            Squared : constant U64 := Extract_Low (CLMUL_Scalar (Acc, Acc));
         begin
            Acc := CRC32C_64_Value (0, Interfaces.Shift_Left (Squared, Natural (Low)));
         end;
      end loop;
      return Acc;
   end XNModP;

   function CRC_Shift (CRC : U32; Byte_Length : Count) return Vector_128 is
      Exponent : constant U64 := U64 (Byte_Length) * 8 - 33;
   begin
      return CLMUL_Scalar (CRC, XNModP (Exponent));
   end CRC_Shift;

   procedure Fold_136_Loop
     (Vector_Ptr  : in out System.Address;
      Stream0_Ptr : in out System.Address;
      Stream1_Ptr : in out System.Address;
      Stream2_Ptr : in out System.Address;
      Iterations  : in out Count;
      CRC0        : in out U32;
      CRC1        : in out U32;
      CRC2        : in out U32;
      K           : Vector_128;
      X           : in out Accumulator_Array) is
   begin
      --  Fixed XMM registers keep the four vector accumulators and four low
      --  products live for the complete pinned 64-vector/72-scalar byte loop.
      --  Loads/stores of X and K are outside the repeated label.
      Asm
        (Template =>
           "movdqu 0(%8), %%xmm0" & ASCII.LF & ASCII.HT &
           "movdqu 16(%8), %%xmm1" & ASCII.LF & ASCII.HT &
           "movdqu 32(%8), %%xmm2" & ASCII.LF & ASCII.HT &
           "movdqu 48(%8), %%xmm3" & ASCII.LF & ASCII.HT &
           "movdqu 0(%9), %%xmm8" & ASCII.LF & ASCII.HT &
           "1:" & ASCII.LF & ASCII.HT &
           "movdqa %%xmm0, %%xmm4" & ASCII.LF & ASCII.HT &
           "pclmulqdq $0, %%xmm8, %%xmm4" & ASCII.LF & ASCII.HT &
           "pclmulqdq $17, %%xmm8, %%xmm0" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, 0(%0), %%xmm4, %%xmm0" & ASCII.LF & ASCII.HT &
           "movdqa %%xmm1, %%xmm5" & ASCII.LF & ASCII.HT &
           "pclmulqdq $0, %%xmm8, %%xmm5" & ASCII.LF & ASCII.HT &
           "pclmulqdq $17, %%xmm8, %%xmm1" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, 16(%0), %%xmm5, %%xmm1" & ASCII.LF & ASCII.HT &
           "movdqa %%xmm2, %%xmm6" & ASCII.LF & ASCII.HT &
           "pclmulqdq $0, %%xmm8, %%xmm6" & ASCII.LF & ASCII.HT &
           "pclmulqdq $17, %%xmm8, %%xmm2" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, 32(%0), %%xmm6, %%xmm2" & ASCII.LF & ASCII.HT &
           "movdqa %%xmm3, %%xmm7" & ASCII.LF & ASCII.HT &
           "pclmulqdq $0, %%xmm8, %%xmm7" & ASCII.LF & ASCII.HT &
           "pclmulqdq $17, %%xmm8, %%xmm3" & ASCII.LF & ASCII.HT &
           "vpternlogq $0x96, 48(%0), %%xmm7, %%xmm3" & ASCII.LF & ASCII.HT &
           "crc32q 0(%1), %q5" & ASCII.LF & ASCII.HT &
           "crc32q 0(%2), %q6" & ASCII.LF & ASCII.HT &
           "crc32q 0(%3), %q7" & ASCII.LF & ASCII.HT &
           "crc32q 8(%1), %q5" & ASCII.LF & ASCII.HT &
           "crc32q 8(%2), %q6" & ASCII.LF & ASCII.HT &
           "crc32q 8(%3), %q7" & ASCII.LF & ASCII.HT &
           "crc32q 16(%1), %q5" & ASCII.LF & ASCII.HT &
           "crc32q 16(%2), %q6" & ASCII.LF & ASCII.HT &
           "crc32q 16(%3), %q7" & ASCII.LF & ASCII.HT &
           "addq $64, %0" & ASCII.LF & ASCII.HT &
           "addq $24, %1" & ASCII.LF & ASCII.HT &
           "addq $24, %2" & ASCII.LF & ASCII.HT &
           "addq $24, %3" & ASCII.LF & ASCII.HT &
           "decq %4" & ASCII.LF & ASCII.HT &
           "jnz 1b" & ASCII.LF & ASCII.HT &
           "movdqu %%xmm0, 0(%8)" & ASCII.LF & ASCII.HT &
           "movdqu %%xmm1, 16(%8)" & ASCII.LF & ASCII.HT &
           "movdqu %%xmm2, 32(%8)" & ASCII.LF & ASCII.HT &
           "movdqu %%xmm3, 48(%8)",
         Outputs =>
           [System.Address'Asm_Output ("+&r", Vector_Ptr),
            System.Address'Asm_Output ("+&r", Stream0_Ptr),
            System.Address'Asm_Output ("+&r", Stream1_Ptr),
            System.Address'Asm_Output ("+&r", Stream2_Ptr),
            Count'Asm_Output ("+&r", Iterations),
            U32'Asm_Output ("+&r", CRC0),
            U32'Asm_Output ("+&r", CRC1),
            U32'Asm_Output ("+&r", CRC2)],
         Inputs   =>
           [System.Address'Asm_Input ("r", X'Address),
            System.Address'Asm_Input ("r", K'Address)],
         Clobber  =>
           "cc,memory,xmm0,xmm1,xmm2,xmm3,xmm4,xmm5,xmm6,xmm7,xmm8",
         Volatile => True);
   end Fold_136_Loop;
   pragma Inline_Always (Fold_136_Loop);

   function Update
     (State : U32;
      Data  : Byte_Array) return U32 is
      CRC0      : U32 := State;
      Pointer   : System.Address := Data'Address;
      Remaining : Count := Count (Data'Length);
   begin
      while Remaining > 0 and then Alignment (Pointer, 8) /= 0 loop
         CRC0 := CRC32C_Byte (CRC0, Pointer);
         Pointer := Next (Pointer, 1);
         Remaining := Remaining - 1;
      end loop;

      --  Advance one word when the now-eight-byte-aligned pointer is not also
      --  sixteen-byte aligned.
      if Alignment (Pointer, 16) = 8 and then Remaining >= 8 then
         CRC0 := CRC32C_64 (CRC0, Pointer);
         Pointer := Next (Pointer, 8);
         Remaining := Remaining - 8;
      end if;

      if Remaining >= 144 then
         declare
            Block_Count : constant Count := (Remaining - 8) / 136;
            K_Length    : constant Count := Block_Count * 24;
            Loop_Count  : Count := Block_Count - 1;
            Main_Loops  : constant Count := Loop_Count;
            Vector_Ptr  : System.Address := Next (Pointer, 64);
            Stream0_Ptr : System.Address := Next (Pointer, Block_Count * 64);
            Stream1_Ptr : System.Address := Next (Stream0_Ptr, K_Length);
            Stream2_Ptr : System.Address := Next (Stream1_Ptr, K_Length);
            CRC1        : U32 := 0;
            CRC2        : U32 := 0;
            X           : Accumulator_Array :=
              (0 => Load_128 (Pointer),
               1 => Load_128 (Next (Pointer, 16)),
               2 => Load_128 (Next (Pointer, 32)),
               3 => Load_128 (Next (Pointer, 48)));
            K_Fold      : constant Vector_128 :=
              (16#0000_0000_740E_EF02#, 16#0000_0000_9E4A_DDF8#);
         begin
            X (0) := Xor_128 (X (0), (U64 (CRC0), 0));
            CRC0 := 0;
            Remaining := Remaining - 136;

            if Loop_Count > 0 then
               Fold_136_Loop
                 (Vector_Ptr, Stream0_Ptr, Stream1_Ptr, Stream2_Ptr,
                  Loop_Count, CRC0, CRC1, CRC2, K_Fold, X);
               Remaining := Remaining - Main_Loops * 136;
            end if;
            Pointer := Stream0_Ptr;

            declare
               K_Reduce_4_To_2 : constant Vector_128 :=
                 (16#0000_0000_F20C_0DFE#, 16#0000_0000_493C_7D27#);
               K_Reduce_2_To_1 : constant Vector_128 :=
                 (16#0000_0000_3DA6_D0CB#, 16#0000_0000_BA4F_C28E#);
               Y0, Y2 : Vector_128;
            begin
               Y0 := CLMUL_Low (X (0), K_Reduce_4_To_2);
               X (0) := CLMUL_High (X (0), K_Reduce_4_To_2);
               Y2 := CLMUL_Low (X (2), K_Reduce_4_To_2);
               X (2) := CLMUL_High (X (2), K_Reduce_4_To_2);
               X (0) := Ternary_Xor_128 (X (0), Y0, X (1));
               X (2) := Ternary_Xor_128 (X (2), Y2, X (3));

               Y0 := CLMUL_Low (X (0), K_Reduce_2_To_1);
               X (0) := CLMUL_High (X (0), K_Reduce_2_To_1);
               X (0) := Ternary_Xor_128 (X (0), Y0, X (2));
            end;

            CRC0 := CRC32C_64 (CRC0, Pointer);
            CRC1 := CRC32C_64 (CRC1, Next (Pointer, K_Length));
            CRC2 := CRC32C_64 (CRC2, Next (Pointer, K_Length * 2));
            CRC0 := CRC32C_64 (CRC0, Next (Pointer, 8));
            CRC1 := CRC32C_64 (CRC1, Next (Pointer, K_Length + 8));
            CRC2 := CRC32C_64 (CRC2, Next (Pointer, K_Length * 2 + 8));
            CRC0 := CRC32C_64 (CRC0, Next (Pointer, 16));
            CRC1 := CRC32C_64 (CRC1, Next (Pointer, K_Length + 16));
            CRC2 := CRC32C_64 (CRC2, Next (Pointer, K_Length * 2 + 16));
            Pointer := Next (Pointer, 24);

            declare
               VC0 : constant Vector_128 := CRC_Shift (CRC0, K_Length * 2 + 8);
               VC1 : constant Vector_128 := CRC_Shift (CRC1, K_Length + 8);
               Combined : constant U32 :=
                 CRC32C_64_Value
                   (CRC32C_64_Value (0, Extract_Low (X (0))),
                    Extract_High (X (0)));
               VCX : constant Vector_128 := CRC_Shift (Combined, K_Length * 3 + 8);
               VC  : constant U64 :=
                 Extract_Low (Xor_128 (VC0, VC1)) xor Extract_Low (VCX);
            begin
               Pointer := Next (Pointer, K_Length * 2);
               CRC0 := CRC32C_64_Value (CRC2, Load_64 (Pointer) xor VC);
            end;
            Pointer := Next (Pointer, 8);
            Remaining := Remaining - 8;
         end;
      end if;

      while Remaining >= 8 loop
         CRC0 := CRC32C_64 (CRC0, Pointer);
         Pointer := Next (Pointer, 8);
         Remaining := Remaining - 8;
      end loop;

      while Remaining > 0 loop
         CRC0 := CRC32C_Byte (CRC0, Pointer);
         Pointer := Next (Pointer, 1);
         Remaining := Remaining - 1;
      end loop;
      return CRC0;
   end Update;

   function Compiled return Boolean is (True);
end Flyology_CRC.CRC32C_X86_AVX512_PCLMUL_V4S3X3;
