--  Generated by tools/generate_catalogue.py; do not edit.
--  Parameter source: https://reveng.sourceforge.io/crc-catalogue/all.htm
--  Versioned input: catalogue/crc-catalogue.toml

--  Folding keys use Flyology CRC's private fold-by-eight layout.

with Flyology_CRC.Width_16;
with Flyology_CRC.Width_32;
with Flyology_CRC.Width_64;

package Generated_CRC_Checks is
   Check_16 : constant array (Flyology_CRC.Width_16.Algorithm) of
     Flyology_CRC.Width_16.Value :=
       (Flyology_CRC.Width_16.ARC => 16#BB3D#,
        Flyology_CRC.Width_16.CDMA2000 => 16#4C06#,
        Flyology_CRC.Width_16.CMS => 16#AEE7#,
        Flyology_CRC.Width_16.DDS_110 => 16#9ECF#,
        Flyology_CRC.Width_16.DECT_R => 16#007E#,
        Flyology_CRC.Width_16.DECT_X => 16#007F#,
        Flyology_CRC.Width_16.DNP => 16#EA82#,
        Flyology_CRC.Width_16.EN_13757 => 16#C2B7#,
        Flyology_CRC.Width_16.GENIBUS => 16#D64E#,
        Flyology_CRC.Width_16.GSM => 16#CE3C#,
        Flyology_CRC.Width_16.IBM_3740 => 16#29B1#,
        Flyology_CRC.Width_16.IBM_SDLC => 16#906E#,
        Flyology_CRC.Width_16.ISO_IEC_14443_3_A => 16#BF05#,
        Flyology_CRC.Width_16.KERMIT => 16#2189#,
        Flyology_CRC.Width_16.LJ1200 => 16#BDF4#,
        Flyology_CRC.Width_16.M17 => 16#772B#,
        Flyology_CRC.Width_16.MAXIM_DOW => 16#44C2#,
        Flyology_CRC.Width_16.MCRF4XX => 16#6F91#,
        Flyology_CRC.Width_16.MODBUS => 16#4B37#,
        Flyology_CRC.Width_16.NRSC_5 => 16#A066#,
        Flyology_CRC.Width_16.OPENSAFETY_A => 16#5D38#,
        Flyology_CRC.Width_16.OPENSAFETY_B => 16#20FE#,
        Flyology_CRC.Width_16.PROFIBUS => 16#A819#,
        Flyology_CRC.Width_16.RIELLO => 16#63D0#,
        Flyology_CRC.Width_16.SPI_FUJITSU => 16#E5CC#,
        Flyology_CRC.Width_16.T10_DIF => 16#D0DB#,
        Flyology_CRC.Width_16.TELEDISK => 16#0FB3#,
        Flyology_CRC.Width_16.TMS37157 => 16#26B1#,
        Flyology_CRC.Width_16.UMTS => 16#FEE8#,
        Flyology_CRC.Width_16.USB => 16#B4C8#,
        Flyology_CRC.Width_16.XMODEM => 16#31C3#);

   Check_32 : constant array (Flyology_CRC.Width_32.Algorithm) of
     Flyology_CRC.Width_32.Value :=
       (Flyology_CRC.Width_32.AIXM => 16#3010BF7F#,
        Flyology_CRC.Width_32.AUTOSAR => 16#1697D06A#,
        Flyology_CRC.Width_32.BASE91_D => 16#87315576#,
        Flyology_CRC.Width_32.BZIP2 => 16#FC891918#,
        Flyology_CRC.Width_32.CD_ROM_EDC => 16#6EC2EDC4#,
        Flyology_CRC.Width_32.CKSUM => 16#765E7680#,
        Flyology_CRC.Width_32.ISCSI => 16#E3069283#,
        Flyology_CRC.Width_32.ISO_HDLC => 16#CBF43926#,
        Flyology_CRC.Width_32.JAMCRC => 16#340BC6D9#,
        Flyology_CRC.Width_32.MEF => 16#D2C22F51#,
        Flyology_CRC.Width_32.MPEG_2 => 16#0376E6E7#,
        Flyology_CRC.Width_32.XFER => 16#BD0BE338#);

   Check_64 : constant array (Flyology_CRC.Width_64.Algorithm) of
     Flyology_CRC.Width_64.Value :=
       (Flyology_CRC.Width_64.ECMA_182 => 16#6C40DF5F0B497347#,
        Flyology_CRC.Width_64.GO_ISO => 16#B90956C775A41001#,
        Flyology_CRC.Width_64.MS => 16#75D4B74F024ECEEA#,
        Flyology_CRC.Width_64.NVME => 16#AE8B14860A799888#,
        Flyology_CRC.Width_64.REDIS => 16#E9C6D914C4B8D9CA#,
        Flyology_CRC.Width_64.WE => 16#62EC59E3F1A4F00A#,
        Flyology_CRC.Width_64.XZ => 16#995DC9BBDF1939FA#);

end Generated_CRC_Checks;
