--  The v12e_v1 CRC32C geometry and constants were generated by
--  corsix/fast-crc32 with `./generate -i neon -p crc32c -a v12e_v1` and then
--  altered and translated to Ada. See THIRD_PARTY_NOTICES.md.

with System.Machine_Code;
with System.Storage_Elements;

package body Flyology_CRC.CRC32C_PMULL_V12E_V1 is
   use System.Machine_Code;
   use type System.Bit_Order;
   use type System.Storage_Elements.Storage_Count;

   subtype U8 is Interfaces.Unsigned_8;
   subtype U32 is Interfaces.Unsigned_32;
   subtype U64 is Interfaces.Unsigned_64;
   subtype Count is System.Storage_Elements.Storage_Count;

   --  The selected AArch64 backend uses the little-endian lane and scalar
   --  load convention on macOS arm64 and Linux aarch64.
   pragma Compile_Time_Error
     (System.Default_Bit_Order /= System.Low_Order_First,
      "the AArch64 CRC32C fusion kernel requires little-endian byte order");

   type Vector is array (0 .. 15) of U8;
   for Vector'Alignment use 16;
   pragma Machine_Attribute (Vector, "vector_type");

   pragma Compile_Time_Error
     (Vector'Size /= 128, "the CRC32C fusion vector must be exactly 128 bits");
   pragma Compile_Time_Error
     (Vector'Alignment /= 16, "the CRC32C fusion vector must be 16-byte aligned");

   type Byte_Block is array (0 .. 15) of U8;

   --  Generated v12e_v1 polynomial constants.  Keeping them as aligned data
   --  lets the leaf load each complete coefficient pair with one vector load
   --  instead of synthesizing both lanes on every checksum call.
   type Vector_Constant is array (0 .. 1) of aliased U64;
   for Vector_Constant'Alignment use 16;

   K_Fold_12 : aliased constant Vector_Constant :=
     (16#0000_0000_A87A_B8A8#, 16#0000_0000_AB7A_FF2A#);
   K_Pair : aliased constant Vector_Constant :=
     (16#0000_0000_F20C_0DFE#, 16#0000_0000_493C_7D27#);
   K_Four : aliased constant Vector_Constant :=
     (16#0000_0000_3DA6_D0CB#, 16#0000_0000_BA4F_C28E#);
   K_Final : aliased constant Vector_Constant :=
     (16#0000_0000_740E_EF02#, 16#0000_0000_9E4A_DDF8#);

   function Update_V12_64_Tail
     (State : U32;
      Data  : Byte_Array) return U32 is
      Pointer : System.Address := Data (Data'First)'Address;
      Result  : U32;
      Bytes    : constant Count := Count (Data'Length);
      Odd_Chunks : constant U32 := U32 (((Bytes - 256) / 192) mod 2);
   begin
      --  Fixed registers follow the pinned Rust v12e_v1 allocation and are
      --  all caller-saved under AAPCS64.  The fixed-tail geometry makes the entire
      --  operation one region: no accumulator crosses the asm boundary and
      --  arbitrary input alignment remains valid for AArch64 LDP.
      Asm
        (Template =>
           "ldp q18, q17, [%x1]" & ASCII.LF & ASCII.HT &
           "ldp q16, q7, [%x1, #32]" & ASCII.LF & ASCII.HT &
           "ldp q19, q6, [%x1, #64]" & ASCII.LF & ASCII.HT &
           "ldp q5, q3, [%x1, #96]" & ASCII.LF & ASCII.HT &
           "ldp q4, q1, [%x1, #128]" & ASCII.LF & ASCII.HT &
           "ldp q2, q0, [%x1, #160]" & ASCII.LF & ASCII.HT &
           "movi v21.2d, #0" & ASCII.LF & ASCII.HT &
           "ins v21.s[0], %w2" & ASCII.LF & ASCII.HT &
           "eor v18.16b, v18.16b, v21.16b" & ASCII.LF & ASCII.HT &
           "ldr q20, [%x4]" & ASCII.LF & ASCII.HT &
           "dup v21.2d, v20.d[0]" & ASCII.LF & ASCII.HT &
           "dup v20.2d, v20.d[1]" & ASCII.LF & ASCII.HT &
           "add x9, %x1, %x3" & ASCII.LF & ASCII.HT &
           "sub x9, x9, #64" & ASCII.LF & ASCII.HT &
           "add %x1, %x1, #192" & ASCII.LF & ASCII.HT &
           ".macro flyology_crc32c_v12_head o0, o1, o2, o3, o4, o5" &
             ASCII.LF & ASCII.HT &
           "pmull v22.1q, v18.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q23, q24, [%x1, #\o0]" & ASCII.LF & ASCII.HT &
           "pmull v25.1q, v17.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q27, q28, [%x1, #\o1]" & ASCII.LF & ASCII.HT &
           "pmull v26.1q, v16.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q31, q8, [%x1, #\o5]" & ASCII.LF & ASCII.HT &
           "pmull2 v18.1q, v18.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull2 v17.1q, v17.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v22.16b, v23.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v23.16b, v24.16b, v25.16b" & ASCII.LF & ASCII.HT &
           "eor v24.16b, v27.16b, v26.16b" & ASCII.LF & ASCII.HT &
           "ldp q25, q27, [%x1, #\o2]" & ASCII.LF & ASCII.HT &
           "pmull v26.1q, v6.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v18.16b, v22.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v16.1q, v16.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v17.16b, v23.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v7.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v19.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v22.16b, v27.16b, v26.16b" & ASCII.LF & ASCII.HT &
           "pmull v23.1q, v5.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v16.16b, v24.16b, v16.16b" & ASCII.LF & ASCII.HT &
           "pmull v27.1q, v3.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q24, q26, [%x1, #\o3]" & ASCII.LF & ASCII.HT &
           "eor v28.16b, v28.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "eor v25.16b, v25.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v4.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v1.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v23.16b, v24.16b, v23.16b" & ASCII.LF & ASCII.HT &
           "eor v26.16b, v26.16b, v27.16b" & ASCII.LF & ASCII.HT &
           "ldp q24, q27, [%x1, #\o4]" & ASCII.LF & ASCII.HT &
           "pmull2 v7.1q, v7.2d, v20.2d" & ASCII.LF & ASCII.HT &
           ".endm" & ASCII.LF & ASCII.HT &
           ".macro flyology_crc32c_v12_tail" & ASCII.LF & ASCII.HT &
           "eor v24.16b, v24.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "eor v27.16b, v27.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v2.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v0.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v7.16b, v28.16b, v7.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v6.1q, v6.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v25.16b, v19.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v5.1q, v5.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull2 v3.1q, v3.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v28.16b, v31.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v4.1q, v4.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v29.16b, v8.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v1.1q, v1.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v6.16b, v22.16b, v6.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v2.1q, v2.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v5.16b, v23.16b, v5.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v0.1q, v0.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v3.16b, v26.16b, v3.16b" & ASCII.LF & ASCII.HT &
           "eor v4.16b, v24.16b, v4.16b" & ASCII.LF & ASCII.HT &
           "eor v1.16b, v27.16b, v1.16b" & ASCII.LF & ASCII.HT &
           "eor v2.16b, v28.16b, v2.16b" & ASCII.LF & ASCII.HT &
           "eor v0.16b, v29.16b, v0.16b" & ASCII.LF & ASCII.HT &
           ".endm" & ASCII.LF & ASCII.HT &
           "tbnz %w8, #0, 2f" & ASCII.LF & ASCII.HT &
           "1:" & ASCII.LF & ASCII.HT &
           "flyology_crc32c_v12_head 0, 32, 64, 96, 128, 160" &
             ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "flyology_crc32c_v12_tail" & ASCII.LF & ASCII.HT &
           "flyology_crc32c_v12_head 192, 224, 256, 288, 320, 352" &
             ASCII.LF & ASCII.HT &
           "add %x1, %x1, #384" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "cmp %x1, x9" & ASCII.LF & ASCII.HT &
           "flyology_crc32c_v12_tail" & ASCII.LF & ASCII.HT &
           "b.ne 1b" & ASCII.LF & ASCII.HT &
           "b 3f" & ASCII.LF & ASCII.HT &
           "2:" & ASCII.LF & ASCII.HT &
           "flyology_crc32c_v12_head 0, 32, 64, 96, 128, 160" &
             ASCII.LF & ASCII.HT &
           "add %x1, %x1, #192" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "cmp %x1, x9" & ASCII.LF & ASCII.HT &
           "flyology_crc32c_v12_tail" & ASCII.LF & ASCII.HT &
           "b.eq 3f" & ASCII.LF & ASCII.HT &
           "b 1b" & ASCII.LF & ASCII.HT &
           "3:" & ASCII.LF & ASCII.HT &
           ".purgem flyology_crc32c_v12_head" & ASCII.LF & ASCII.HT &
           ".purgem flyology_crc32c_v12_tail" & ASCII.LF & ASCII.HT &
           "ldr q20, [%x5]" & ASCII.LF & ASCII.HT &
           "dup v21.2d, v20.d[0]" & ASCII.LF & ASCII.HT &
           "dup v20.2d, v20.d[1]" & ASCII.LF & ASCII.HT &
           "ldr q25, [%x7]" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v18.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v18.1q, v18.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull v23.1q, v19.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v18.16b, v18.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v16.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v16.1q, v16.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v17.16b, v17.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "eor v18.16b, v19.16b, v23.16b" & ASCII.LF & ASCII.HT &
           "ldr q23, [%x6]" & ASCII.LF & ASCII.HT &
           "dup v19.2d, v23.d[0]" & ASCII.LF & ASCII.HT &
           "dup v23.2d, v23.d[1]" & ASCII.LF & ASCII.HT &
           "pmull v24.1q, v17.1d, v19.1d" & ASCII.LF & ASCII.HT &
           "eor v16.16b, v16.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v6.16b, v6.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v17.1q, v17.2d, v23.2d" & ASCII.LF & ASCII.HT &
           "pmull v18.1q, v5.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v5.1q, v5.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v16.16b, v16.16b, v24.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v4.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v7.16b, v7.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v4.1q, v4.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull v17.1q, v6.1d, v19.1d" & ASCII.LF & ASCII.HT &
           "eor v5.16b, v5.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "dup v18.2d, v25.d[0]" & ASCII.LF & ASCII.HT &
           "eor v7.16b, v7.16b, v16.16b" & ASCII.LF & ASCII.HT &
           "dup v16.2d, v25.d[1]" & ASCII.LF & ASCII.HT &
           "pmull2 v6.1q, v6.2d, v23.2d" & ASCII.LF & ASCII.HT &
           "eor v4.16b, v4.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v5.16b, v5.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "pmull v17.1q, v7.1d, v18.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v7.1q, v7.2d, v16.2d" & ASCII.LF & ASCII.HT &
           "eor v1.16b, v1.16b, v4.16b" & ASCII.LF & ASCII.HT &
           "pmull v21.1q, v2.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v5.16b, v5.16b, v6.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v2.1q, v2.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v4.16b, v5.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "eor v3.16b, v3.16b, v7.16b" & ASCII.LF & ASCII.HT &
           "pmull v5.1q, v1.1d, v19.1d" & ASCII.LF & ASCII.HT &
           "eor v2.16b, v2.16b, v21.16b" & ASCII.LF & ASCII.HT &
           "eor v3.16b, v3.16b, v4.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v1.1q, v1.2d, v23.2d" & ASCII.LF & ASCII.HT &
           "eor v2.16b, v2.16b, v5.16b" & ASCII.LF & ASCII.HT &
           "pmull v4.1q, v3.1d, v18.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v3.1q, v3.2d, v16.2d" & ASCII.LF & ASCII.HT &
           "eor v1.16b, v2.16b, v1.16b" & ASCII.LF & ASCII.HT &
           "eor v1.16b, v1.16b, v4.16b" & ASCII.LF & ASCII.HT &
           "eor v0.16b, v0.16b, v3.16b" & ASCII.LF & ASCII.HT &
           "eor v0.16b, v0.16b, v1.16b" & ASCII.LF & ASCII.HT &
           "umov x9, v0.d[0]" & ASCII.LF & ASCII.HT &
           "umov x10, v0.d[1]" & ASCII.LF & ASCII.HT &
           "crc32cx %w0, wzr, x9" & ASCII.LF & ASCII.HT &
           "crc32cx %w0, %w0, x10" & ASCII.LF & ASCII.HT &
           "movi v20.2d, #0" & ASCII.LF & ASCII.HT &
           "ins v20.s[0], %w0" & ASCII.LF & ASCII.HT &
           "ldp q19, q17, [%x1]" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v19.16b, v20.16b" & ASCII.LF & ASCII.HT &
           "ldr q20, [%x5]" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v19.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v21.16b, v19.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v21.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "ldp q17, q18, [%x1, #32]" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v19.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v21.16b, v19.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v21.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v19.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v21.16b, v19.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v21.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "umov x9, v19.d[0]" & ASCII.LF & ASCII.HT &
           "umov x10, v19.d[1]" & ASCII.LF & ASCII.HT &
           "crc32cx %w0, wzr, x9" & ASCII.LF & ASCII.HT &
           "crc32cx %w0, %w0, x10",
         Outputs =>
           [U32'Asm_Output ("=&r", Result),
            System.Address'Asm_Output ("+&r", Pointer)],
         Inputs   =>
           [U32'Asm_Input ("r", State),
            Count'Asm_Input ("r", Bytes),
            System.Address'Asm_Input ("r", K_Fold_12'Address),
            System.Address'Asm_Input ("r", K_Pair'Address),
            System.Address'Asm_Input ("r", K_Four'Address),
            System.Address'Asm_Input ("r", K_Final'Address),
            U32'Asm_Input ("r", Odd_Chunks)],
         Clobber  =>
           "cc,memory,x9,x10," &
           "v0,v1,v2,v3,v4,v5,v6,v7,v8,v16,v17,v18,v19,v20,v21,v22,v23," &
           "v24,v25,v26,v27,v28,v29,v30,v31",
         Volatile => True);
      return Result;
   end Update_V12_64_Tail;

   function Update_1024_V12
     (State  : U32;
      Source : System.Address) return U32 is
      Pointer : constant System.Address := Source;
      Result  : U32;
   begin
      --  Fixed registers follow the pinned Rust v12e_v1 allocation and are
      --  all caller-saved under AAPCS64.  The exact 1,024-byte geometry keeps the entire
      --  operation in one unrolled region: no accumulator crosses the asm boundary,
      --  all payload offsets fit LDP immediates, and arbitrary alignment remains valid.
      Asm
        (Template =>
           "ldp q18, q17, [%x1]" & ASCII.LF & ASCII.HT &
           "ldp q16, q7, [%x1, #32]" & ASCII.LF & ASCII.HT &
           "ldp q19, q6, [%x1, #64]" & ASCII.LF & ASCII.HT &
           "ldp q5, q3, [%x1, #96]" & ASCII.LF & ASCII.HT &
           "ldp q4, q1, [%x1, #128]" & ASCII.LF & ASCII.HT &
           "ldp q2, q0, [%x1, #160]" & ASCII.LF & ASCII.HT &
           "movi v21.2d, #0" & ASCII.LF & ASCII.HT &
           "ins v21.s[0], %w2" & ASCII.LF & ASCII.HT &
           "eor v18.16b, v18.16b, v21.16b" & ASCII.LF & ASCII.HT &
           "ldr q20, [%x3]" & ASCII.LF & ASCII.HT &
           "dup v21.2d, v20.d[0]" & ASCII.LF & ASCII.HT &
           "dup v20.2d, v20.d[1]" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v18.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q23, q24, [%x1, #192]" & ASCII.LF & ASCII.HT &
           "pmull v25.1q, v17.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q27, q28, [%x1, #224]" & ASCII.LF & ASCII.HT &
           "pmull v26.1q, v16.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q31, q8, [%x1, #352]" & ASCII.LF & ASCII.HT &
           "pmull2 v18.1q, v18.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull2 v17.1q, v17.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v22.16b, v23.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v23.16b, v24.16b, v25.16b" & ASCII.LF & ASCII.HT &
           "eor v24.16b, v27.16b, v26.16b" & ASCII.LF & ASCII.HT &
           "ldp q25, q27, [%x1, #256]" & ASCII.LF & ASCII.HT &
           "pmull v26.1q, v6.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v18.16b, v22.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v16.1q, v16.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v17.16b, v23.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v7.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v19.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v22.16b, v27.16b, v26.16b" & ASCII.LF & ASCII.HT &
           "pmull v23.1q, v5.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v16.16b, v24.16b, v16.16b" & ASCII.LF & ASCII.HT &
           "pmull v27.1q, v3.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q24, q26, [%x1, #288]" & ASCII.LF & ASCII.HT &
           "eor v28.16b, v28.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "eor v25.16b, v25.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v4.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v1.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v23.16b, v24.16b, v23.16b" & ASCII.LF & ASCII.HT &
           "eor v26.16b, v26.16b, v27.16b" & ASCII.LF & ASCII.HT &
           "ldp q24, q27, [%x1, #320]" & ASCII.LF & ASCII.HT &
           "pmull2 v7.1q, v7.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v24.16b, v24.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "eor v27.16b, v27.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v2.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v0.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v7.16b, v28.16b, v7.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v6.1q, v6.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v25.16b, v19.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v5.1q, v5.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull2 v3.1q, v3.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v28.16b, v31.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v4.1q, v4.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v29.16b, v8.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v1.1q, v1.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v6.16b, v22.16b, v6.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v2.1q, v2.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v5.16b, v23.16b, v5.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v0.1q, v0.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v3.16b, v26.16b, v3.16b" & ASCII.LF & ASCII.HT &
           "eor v4.16b, v24.16b, v4.16b" & ASCII.LF & ASCII.HT &
           "eor v1.16b, v27.16b, v1.16b" & ASCII.LF & ASCII.HT &
           "eor v2.16b, v28.16b, v2.16b" & ASCII.LF & ASCII.HT &
           "eor v0.16b, v29.16b, v0.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v18.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q23, q24, [%x1, #384]" & ASCII.LF & ASCII.HT &
           "pmull v25.1q, v17.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q27, q28, [%x1, #416]" & ASCII.LF & ASCII.HT &
           "pmull v26.1q, v16.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q31, q8, [%x1, #544]" & ASCII.LF & ASCII.HT &
           "pmull2 v18.1q, v18.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull2 v17.1q, v17.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v22.16b, v23.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v23.16b, v24.16b, v25.16b" & ASCII.LF & ASCII.HT &
           "eor v24.16b, v27.16b, v26.16b" & ASCII.LF & ASCII.HT &
           "ldp q25, q27, [%x1, #448]" & ASCII.LF & ASCII.HT &
           "pmull v26.1q, v6.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v18.16b, v22.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v16.1q, v16.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v17.16b, v23.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v7.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v19.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v22.16b, v27.16b, v26.16b" & ASCII.LF & ASCII.HT &
           "pmull v23.1q, v5.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v16.16b, v24.16b, v16.16b" & ASCII.LF & ASCII.HT &
           "pmull v27.1q, v3.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q24, q26, [%x1, #480]" & ASCII.LF & ASCII.HT &
           "eor v28.16b, v28.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "eor v25.16b, v25.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v4.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v1.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v23.16b, v24.16b, v23.16b" & ASCII.LF & ASCII.HT &
           "eor v26.16b, v26.16b, v27.16b" & ASCII.LF & ASCII.HT &
           "ldp q24, q27, [%x1, #512]" & ASCII.LF & ASCII.HT &
           "pmull2 v7.1q, v7.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v24.16b, v24.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "eor v27.16b, v27.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v2.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v0.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v7.16b, v28.16b, v7.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v6.1q, v6.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v25.16b, v19.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v5.1q, v5.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull2 v3.1q, v3.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v28.16b, v31.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v4.1q, v4.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v29.16b, v8.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v1.1q, v1.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v6.16b, v22.16b, v6.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v2.1q, v2.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v5.16b, v23.16b, v5.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v0.1q, v0.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v3.16b, v26.16b, v3.16b" & ASCII.LF & ASCII.HT &
           "eor v4.16b, v24.16b, v4.16b" & ASCII.LF & ASCII.HT &
           "eor v1.16b, v27.16b, v1.16b" & ASCII.LF & ASCII.HT &
           "eor v2.16b, v28.16b, v2.16b" & ASCII.LF & ASCII.HT &
           "eor v0.16b, v29.16b, v0.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v18.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q23, q24, [%x1, #576]" & ASCII.LF & ASCII.HT &
           "pmull v25.1q, v17.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q27, q28, [%x1, #608]" & ASCII.LF & ASCII.HT &
           "pmull v26.1q, v16.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q31, q8, [%x1, #736]" & ASCII.LF & ASCII.HT &
           "pmull2 v18.1q, v18.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull2 v17.1q, v17.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v22.16b, v23.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v23.16b, v24.16b, v25.16b" & ASCII.LF & ASCII.HT &
           "eor v24.16b, v27.16b, v26.16b" & ASCII.LF & ASCII.HT &
           "ldp q25, q27, [%x1, #640]" & ASCII.LF & ASCII.HT &
           "pmull v26.1q, v6.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v18.16b, v22.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v16.1q, v16.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v17.16b, v23.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v7.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v19.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v22.16b, v27.16b, v26.16b" & ASCII.LF & ASCII.HT &
           "pmull v23.1q, v5.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v16.16b, v24.16b, v16.16b" & ASCII.LF & ASCII.HT &
           "pmull v27.1q, v3.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q24, q26, [%x1, #672]" & ASCII.LF & ASCII.HT &
           "eor v28.16b, v28.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "eor v25.16b, v25.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v4.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v1.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v23.16b, v24.16b, v23.16b" & ASCII.LF & ASCII.HT &
           "eor v26.16b, v26.16b, v27.16b" & ASCII.LF & ASCII.HT &
           "ldp q24, q27, [%x1, #704]" & ASCII.LF & ASCII.HT &
           "pmull2 v7.1q, v7.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v24.16b, v24.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "eor v27.16b, v27.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v2.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v0.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v7.16b, v28.16b, v7.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v6.1q, v6.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v25.16b, v19.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v5.1q, v5.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull2 v3.1q, v3.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v28.16b, v31.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v4.1q, v4.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v29.16b, v8.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v1.1q, v1.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v6.16b, v22.16b, v6.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v2.1q, v2.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v5.16b, v23.16b, v5.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v0.1q, v0.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v3.16b, v26.16b, v3.16b" & ASCII.LF & ASCII.HT &
           "eor v4.16b, v24.16b, v4.16b" & ASCII.LF & ASCII.HT &
           "eor v1.16b, v27.16b, v1.16b" & ASCII.LF & ASCII.HT &
           "eor v2.16b, v28.16b, v2.16b" & ASCII.LF & ASCII.HT &
           "eor v0.16b, v29.16b, v0.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v18.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q23, q24, [%x1, #768]" & ASCII.LF & ASCII.HT &
           "pmull v25.1q, v17.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q27, q28, [%x1, #800]" & ASCII.LF & ASCII.HT &
           "pmull v26.1q, v16.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q31, q8, [%x1, #928]" & ASCII.LF & ASCII.HT &
           "pmull2 v18.1q, v18.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull2 v17.1q, v17.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v22.16b, v23.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v23.16b, v24.16b, v25.16b" & ASCII.LF & ASCII.HT &
           "eor v24.16b, v27.16b, v26.16b" & ASCII.LF & ASCII.HT &
           "ldp q25, q27, [%x1, #832]" & ASCII.LF & ASCII.HT &
           "pmull v26.1q, v6.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v18.16b, v22.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v16.1q, v16.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v17.16b, v23.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v7.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v19.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v22.16b, v27.16b, v26.16b" & ASCII.LF & ASCII.HT &
           "pmull v23.1q, v5.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v16.16b, v24.16b, v16.16b" & ASCII.LF & ASCII.HT &
           "pmull v27.1q, v3.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "ldp q24, q26, [%x1, #864]" & ASCII.LF & ASCII.HT &
           "eor v28.16b, v28.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "eor v25.16b, v25.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v4.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v1.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v23.16b, v24.16b, v23.16b" & ASCII.LF & ASCII.HT &
           "eor v26.16b, v26.16b, v27.16b" & ASCII.LF & ASCII.HT &
           "ldp q24, q27, [%x1, #896]" & ASCII.LF & ASCII.HT &
           "pmull2 v7.1q, v7.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v24.16b, v24.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "eor v27.16b, v27.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull v29.1q, v2.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull v30.1q, v0.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v7.16b, v28.16b, v7.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v6.1q, v6.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v25.16b, v19.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v5.1q, v5.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull2 v3.1q, v3.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v28.16b, v31.16b, v29.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v4.1q, v4.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v29.16b, v8.16b, v30.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v1.1q, v1.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v6.16b, v22.16b, v6.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v2.1q, v2.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v5.16b, v23.16b, v5.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v0.1q, v0.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v3.16b, v26.16b, v3.16b" & ASCII.LF & ASCII.HT &
           "eor v4.16b, v24.16b, v4.16b" & ASCII.LF & ASCII.HT &
           "eor v1.16b, v27.16b, v1.16b" & ASCII.LF & ASCII.HT &
           "eor v2.16b, v28.16b, v2.16b" & ASCII.LF & ASCII.HT &
           "eor v0.16b, v29.16b, v0.16b" & ASCII.LF & ASCII.HT &
           "ldr q20, [%x4]" & ASCII.LF & ASCII.HT &
           "dup v21.2d, v20.d[0]" & ASCII.LF & ASCII.HT &
           "dup v20.2d, v20.d[1]" & ASCII.LF & ASCII.HT &
           "ldr q25, [%x6]" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v18.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v18.1q, v18.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull v23.1q, v19.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v18.16b, v18.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v16.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v16.1q, v16.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v17.16b, v17.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "eor v18.16b, v19.16b, v23.16b" & ASCII.LF & ASCII.HT &
           "ldr q23, [%x5]" & ASCII.LF & ASCII.HT &
           "dup v19.2d, v23.d[0]" & ASCII.LF & ASCII.HT &
           "dup v23.2d, v23.d[1]" & ASCII.LF & ASCII.HT &
           "pmull v24.1q, v17.1d, v19.1d" & ASCII.LF & ASCII.HT &
           "eor v16.16b, v16.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v6.16b, v6.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v17.1q, v17.2d, v23.2d" & ASCII.LF & ASCII.HT &
           "pmull v18.1q, v5.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v5.1q, v5.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v16.16b, v16.16b, v24.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v4.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v7.16b, v7.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v4.1q, v4.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "pmull v17.1q, v6.1d, v19.1d" & ASCII.LF & ASCII.HT &
           "eor v5.16b, v5.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "dup v18.2d, v25.d[0]" & ASCII.LF & ASCII.HT &
           "eor v7.16b, v7.16b, v16.16b" & ASCII.LF & ASCII.HT &
           "dup v16.2d, v25.d[1]" & ASCII.LF & ASCII.HT &
           "pmull2 v6.1q, v6.2d, v23.2d" & ASCII.LF & ASCII.HT &
           "eor v4.16b, v4.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v5.16b, v5.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "pmull v17.1q, v7.1d, v18.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v7.1q, v7.2d, v16.2d" & ASCII.LF & ASCII.HT &
           "eor v1.16b, v1.16b, v4.16b" & ASCII.LF & ASCII.HT &
           "pmull v21.1q, v2.1d, v21.1d" & ASCII.LF & ASCII.HT &
           "eor v5.16b, v5.16b, v6.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v2.1q, v2.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v4.16b, v5.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "eor v3.16b, v3.16b, v7.16b" & ASCII.LF & ASCII.HT &
           "pmull v5.1q, v1.1d, v19.1d" & ASCII.LF & ASCII.HT &
           "eor v2.16b, v2.16b, v21.16b" & ASCII.LF & ASCII.HT &
           "eor v3.16b, v3.16b, v4.16b" & ASCII.LF & ASCII.HT &
           "pmull2 v1.1q, v1.2d, v23.2d" & ASCII.LF & ASCII.HT &
           "eor v2.16b, v2.16b, v5.16b" & ASCII.LF & ASCII.HT &
           "pmull v4.1q, v3.1d, v18.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v3.1q, v3.2d, v16.2d" & ASCII.LF & ASCII.HT &
           "eor v1.16b, v2.16b, v1.16b" & ASCII.LF & ASCII.HT &
           "eor v1.16b, v1.16b, v4.16b" & ASCII.LF & ASCII.HT &
           "eor v0.16b, v0.16b, v3.16b" & ASCII.LF & ASCII.HT &
           "eor v0.16b, v0.16b, v1.16b" & ASCII.LF & ASCII.HT &
           "umov x9, v0.d[0]" & ASCII.LF & ASCII.HT &
           "umov x10, v0.d[1]" & ASCII.LF & ASCII.HT &
           "crc32cx %w0, wzr, x9" & ASCII.LF & ASCII.HT &
           "crc32cx %w0, %w0, x10" & ASCII.LF & ASCII.HT &
           "movi v20.2d, #0" & ASCII.LF & ASCII.HT &
           "ins v20.s[0], %w0" & ASCII.LF & ASCII.HT &
           "ldp q19, q17, [%x1, #960]" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v19.16b, v20.16b" & ASCII.LF & ASCII.HT &
           "ldr q20, [%x4]" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v19.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v21.16b, v19.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v21.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "ldp q17, q18, [%x1, #992]" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v19.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v21.16b, v19.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v21.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v19.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor v21.16b, v19.16b, v22.16b" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v21.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "umov x9, v19.d[0]" & ASCII.LF & ASCII.HT &
           "umov x10, v19.d[1]" & ASCII.LF & ASCII.HT &
           "crc32cx %w0, wzr, x9" & ASCII.LF & ASCII.HT &
           "crc32cx %w0, %w0, x10",
         Outputs => U32'Asm_Output ("=&r", Result),
         Inputs   =>
           [System.Address'Asm_Input ("r", Pointer),
            U32'Asm_Input ("r", State),
            System.Address'Asm_Input ("r", K_Fold_12'Address),
            System.Address'Asm_Input ("r", K_Pair'Address),
            System.Address'Asm_Input ("r", K_Four'Address),
            System.Address'Asm_Input ("r", K_Final'Address)],
         Clobber  =>
           "cc,memory,x9,x10," &
           "v0,v1,v2,v3,v4,v5,v6,v7,v8,v16,v17,v18,v19,v20,v21,v22,v23," &
           "v24,v25,v26,v27,v28,v29,v30,v31",
         Volatile => True);
      return Result;
   end Update_1024_V12;

   function Next
     (Source : System.Address;
      Bytes  : Count) return System.Address is
     (System.Storage_Elements."+"
        (Source, System.Storage_Elements.Storage_Offset (Bytes)));
   pragma Inline_Always (Next);

   function Alignment
     (Source : System.Address;
      Bytes  : Count) return Count is
     (Count
        (System.Storage_Elements."mod"
           (Source, System.Storage_Elements.Storage_Offset (Bytes))));
   pragma Inline_Always (Alignment);

   function Load_Byte (Source : System.Address) return U32 is
      Item : U8 with Import, Address => Source;
   begin
      return U32 (Item);
   end Load_Byte;
   pragma Inline_Always (Load_Byte);

   function Load_64 (Source : System.Address) return U64 is
      Item : U64 with Import, Address => Source;
   begin
      return Item;
   end Load_64;
   pragma Inline_Always (Load_64);

   function Load_128 (Source : System.Address) return Vector is
      Bytes  : Byte_Block with Import, Address => Source;
      Result : Vector;
   begin
      Asm
        (Template => "ldr %q0, %1",
         Outputs  => Vector'Asm_Output ("=&w", Result),
         Inputs   => Byte_Block'Asm_Input ("Q", Bytes));
      return Result;
   end Load_128;
   pragma Inline_Always (Load_128);

   function Pair (Low, High : U64) return Vector is
      Result : Vector;
   begin
      Asm
        (Template =>
           "ins %0.d[0], %x1" & ASCII.LF & ASCII.HT &
           "ins %0.d[1], %x2",
         Outputs => Vector'Asm_Output ("=&w", Result),
         Inputs  =>
           [U64'Asm_Input ("r", Low),
            U64'Asm_Input ("r", High)]);
      return Result;
   end Pair;
   pragma Inline_Always (Pair);

   function Xor_128 (Left, Right : Vector) return Vector is
      Result : Vector;
   begin
      Asm
        (Template => "eor %0.16b, %1.16b, %2.16b",
         Outputs  => Vector'Asm_Output ("=&w", Result),
         Inputs   =>
           [Vector'Asm_Input ("w", Left),
            Vector'Asm_Input ("w", Right)]);
      return Result;
   end Xor_128;
   pragma Inline_Always (Xor_128);

   function Fold_16
     (Current, Coefficient, Data : Vector) return Vector is
      Result      : Vector;
      Low_Product : Vector;
   begin
      Asm
        (Template =>
           "pmull %1.1q, %2.1d, %3.1d" & ASCII.LF & ASCII.HT &
           "pmull2 %0.1q, %2.2d, %3.2d" & ASCII.LF & ASCII.HT &
           "eor %0.16b, %0.16b, %1.16b" & ASCII.LF & ASCII.HT &
           "eor %0.16b, %0.16b, %4.16b",
         Outputs =>
           [Vector'Asm_Output ("=&w", Result),
            Vector'Asm_Output ("=&w", Low_Product)],
         Inputs  =>
           [Vector'Asm_Input ("w", Current),
            Vector'Asm_Input ("w", Coefficient),
            Vector'Asm_Input ("w", Data)]);
      return Result;
   end Fold_16;
   pragma Inline_Always (Fold_16);

   function Low_Lane (Item : Vector) return U64 is
      Result : U64;
   begin
      Asm
        (Template => "umov %x0, %1.d[0]",
         Outputs  => U64'Asm_Output ("=r", Result),
         Inputs   => Vector'Asm_Input ("w", Item));
      return Result;
   end Low_Lane;
   pragma Inline_Always (Low_Lane);

   function High_Lane (Item : Vector) return U64 is
      Result : U64;
   begin
      Asm
        (Template => "umov %x0, %1.d[1]",
         Outputs  => U64'Asm_Output ("=r", Result),
         Inputs   => Vector'Asm_Input ("w", Item));
      return Result;
   end High_Lane;
   pragma Inline_Always (High_Lane);

   function CRC32C_Byte (CRC, Item : U32) return U32 is
      Result : U32;
   begin
      Asm
        (Template => "crc32cb %w0, %w1, %w2",
         Outputs  => U32'Asm_Output ("=r", Result),
         Inputs   =>
           [U32'Asm_Input ("r", CRC),
            U32'Asm_Input ("r", Item)]);
      return Result;
   end CRC32C_Byte;
   pragma Inline_Always (CRC32C_Byte);

   function CRC32C_64 (CRC : U32; Item : U64) return U32 is
      Result : U32;
   begin
      Asm
        (Template => "crc32cx %w0, %w1, %x2",
         Outputs  => U32'Asm_Output ("=r", Result),
         Inputs   =>
           [U32'Asm_Input ("r", CRC),
            U64'Asm_Input ("r", Item)]);
      return Result;
   end CRC32C_64;
   pragma Inline_Always (CRC32C_64);

   function Update
     (State : U32;
      Data  : Byte_Array) return U32 is
      CRC       : U32 := State;
      Pointer   : System.Address := Data'Address;
      Remaining : Count := Count (Data'Length);
      K         : Vector;
      X0        : Vector;
      X1        : Vector;
      X2        : Vector;
      X3        : Vector;
      X4        : Vector;
      X5        : Vector;
      X6        : Vector;
      X7        : Vector;
      X8        : Vector;
      X9        : Vector;
      X10       : Vector;
      X11       : Vector;
   begin
      if Remaining = 0 then
         return CRC;
      end if;

      --  The CRC-only small path aligns to eight bytes, processes eight
      --  scalar words per iteration, and consumes arbitrary tails.
      if Remaining < 128 then
         while Remaining > 0 and then Alignment (Pointer, 8) /= 0 loop
            CRC := CRC32C_Byte (CRC, Load_Byte (Pointer));
            Pointer := Next (Pointer, 1);
            Remaining := Remaining - 1;
         end loop;

         while Remaining >= 64 loop
            CRC := CRC32C_64 (CRC, Load_64 (Pointer));
            CRC := CRC32C_64 (CRC, Load_64 (Next (Pointer, 8)));
            CRC := CRC32C_64 (CRC, Load_64 (Next (Pointer, 16)));
            CRC := CRC32C_64 (CRC, Load_64 (Next (Pointer, 24)));
            CRC := CRC32C_64 (CRC, Load_64 (Next (Pointer, 32)));
            CRC := CRC32C_64 (CRC, Load_64 (Next (Pointer, 40)));
            CRC := CRC32C_64 (CRC, Load_64 (Next (Pointer, 48)));
            CRC := CRC32C_64 (CRC, Load_64 (Next (Pointer, 56)));
            Pointer := Next (Pointer, 64);
            Remaining := Remaining - 64;
         end loop;

         while Remaining >= 8 loop
            CRC := CRC32C_64 (CRC, Load_64 (Pointer));
            Pointer := Next (Pointer, 8);
            Remaining := Remaining - 8;
         end loop;

         while Remaining > 0 loop
            CRC := CRC32C_Byte (CRC, Load_Byte (Pointer));
            Pointer := Next (Pointer, 1);
            Remaining := Remaining - 1;
         end loop;
         return CRC;
      end if;

      --  Align exactly as crc32_iscsi_v12e_v1: first to eight bytes, then
      --  consume one word when necessary to reach a 16-byte vector boundary.
      while Remaining > 0 and then Alignment (Pointer, 8) /= 0 loop
         CRC := CRC32C_Byte (CRC, Load_Byte (Pointer));
         Pointer := Next (Pointer, 1);
         Remaining := Remaining - 1;
      end loop;

      if Alignment (Pointer, 16) /= 0 and then Remaining >= 8 then
         CRC := CRC32C_64 (CRC, Load_64 (Pointer));
         Pointer := Next (Pointer, 8);
         Remaining := Remaining - 8;
      end if;

      if Remaining >= 192 then
         X0 := Load_128 (Pointer);
         X1 := Load_128 (Next (Pointer, 16));
         X2 := Load_128 (Next (Pointer, 32));
         X3 := Load_128 (Next (Pointer, 48));
         X4 := Load_128 (Next (Pointer, 64));
         X5 := Load_128 (Next (Pointer, 80));
         X6 := Load_128 (Next (Pointer, 96));
         X7 := Load_128 (Next (Pointer, 112));
         X8 := Load_128 (Next (Pointer, 128));
         X9 := Load_128 (Next (Pointer, 144));
         X10 := Load_128 (Next (Pointer, 160));
         X11 := Load_128 (Next (Pointer, 176));
         X0 := Xor_128 (X0, Pair (U64 (CRC), 0));
         Pointer := Next (Pointer, 192);
         Remaining := Remaining - 192;

         --  Exact v12e_v1 fold-by-twelve key pair.
         K := Load_128 (K_Fold_12'Address);
         while Remaining >= 192 loop
            X0 := Fold_16 (X0, K, Load_128 (Pointer));
            X1 := Fold_16 (X1, K, Load_128 (Next (Pointer, 16)));
            X2 := Fold_16 (X2, K, Load_128 (Next (Pointer, 32)));
            X3 := Fold_16 (X3, K, Load_128 (Next (Pointer, 48)));
            X4 := Fold_16 (X4, K, Load_128 (Next (Pointer, 64)));
            X5 := Fold_16 (X5, K, Load_128 (Next (Pointer, 80)));
            X6 := Fold_16 (X6, K, Load_128 (Next (Pointer, 96)));
            X7 := Fold_16 (X7, K, Load_128 (Next (Pointer, 112)));
            X8 := Fold_16 (X8, K, Load_128 (Next (Pointer, 128)));
            X9 := Fold_16 (X9, K, Load_128 (Next (Pointer, 144)));
            X10 := Fold_16 (X10, K, Load_128 (Next (Pointer, 160)));
            X11 := Fold_16 (X11, K, Load_128 (Next (Pointer, 176)));
            Pointer := Next (Pointer, 192);
            Remaining := Remaining - 192;
         end loop;

         --  Exact pairwise, four-lane, then final v12e_v1 reduction keys.
         K := Load_128 (K_Pair'Address);
         X0 := Fold_16 (X0, K, X1);
         X2 := Fold_16 (X2, K, X3);
         X4 := Fold_16 (X4, K, X5);
         X6 := Fold_16 (X6, K, X7);
         X8 := Fold_16 (X8, K, X9);
         X10 := Fold_16 (X10, K, X11);

         K := Load_128 (K_Four'Address);
         X0 := Fold_16 (X0, K, X2);
         X4 := Fold_16 (X4, K, X6);
         X8 := Fold_16 (X8, K, X10);

         K := Load_128 (K_Final'Address);
         X0 := Fold_16 (X0, K, X4);
         X0 := Fold_16 (X0, K, X8);

         CRC := CRC32C_64 (0, Low_Lane (X0));
         CRC := CRC32C_64 (CRC, High_Lane (X0));
      end if;

      if Remaining >= 16 then
         X0 := Xor_128 (Load_128 (Pointer), Pair (U64 (CRC), 0));
         Pointer := Next (Pointer, 16);
         Remaining := Remaining - 16;
         K := Load_128 (K_Pair'Address);
         while Remaining >= 16 loop
            X0 := Fold_16 (X0, K, Load_128 (Pointer));
            Pointer := Next (Pointer, 16);
            Remaining := Remaining - 16;
         end loop;
         CRC := CRC32C_64 (0, Low_Lane (X0));
         CRC := CRC32C_64 (CRC, High_Lane (X0));
      end if;

      while Remaining >= 8 loop
         CRC := CRC32C_64 (CRC, Load_64 (Pointer));
         Pointer := Next (Pointer, 8);
         Remaining := Remaining - 8;
      end loop;

      while Remaining > 0 loop
         CRC := CRC32C_Byte (CRC, Load_Byte (Pointer));
         Pointer := Next (Pointer, 1);
         Remaining := Remaining - 1;
      end loop;

      return CRC;
   end Update;
end Flyology_CRC.CRC32C_PMULL_V12E_V1;
