--  The v9s3x2e_s3 CRC32C geometry and constants were generated by
--  corsix/fast-crc32 with
--  `./generate -i neon_eor3 -p crc32c -a v9s3x2e_s3` and then altered and
--  translated to Ada. See THIRD_PARTY_NOTICES.md.

with System.Machine_Code;
with System.Storage_Elements;

package body Flyology_CRC.CRC32C_PMULL_EOR3_V9S3X2E_S3 is
   use System.Machine_Code;
   use type Interfaces.Unsigned_32;
   use type Interfaces.Unsigned_64;
   use type System.Bit_Order;
   use type System.Storage_Elements.Storage_Count;

   subtype U8 is Interfaces.Unsigned_8;
   subtype U32 is Interfaces.Unsigned_32;
   subtype U64 is Interfaces.Unsigned_64;
   subtype Count is System.Storage_Elements.Storage_Count;

   --  The selected AArch64 backend uses a little-endian scalar and lane
   --  convention.
   pragma Compile_Time_Error
     (System.Default_Bit_Order /= System.Low_Order_First,
      "the AArch64 CRC32C EOR3 kernel requires little-endian byte order");

   type Vector is array (0 .. 15) of U8;
   for Vector'Alignment use 16;
   pragma Machine_Attribute (Vector, "vector_type");

   --  The pinned v9s3x2e_s3 kernel has exactly nine folding streams.  This
   --  private array only transfers their state into and out of the asm loop.
   type Accumulator_Array is array (Natural range 0 .. 8) of Vector;
   for Accumulator_Array'Alignment use 16;

   pragma Compile_Time_Error
     (Vector'Size /= 128, "the CRC32C EOR3 vector must be exactly 128 bits");
   pragma Compile_Time_Error
     (Vector'Alignment /= 16, "the CRC32C EOR3 vector must be 16-byte aligned");

   type Byte_Block is array (0 .. 15) of U8;

   type V12_Key is array (0 .. 1) of aliased U64;
   for V12_Key'Alignment use 16;

   --  Generated v12e_v1 polynomial constants used only by the exact-1KiB
   --  whole-operation leaf below.
   V12_K_Fold_12 : aliased constant V12_Key :=
     (16#0000_0000_A87A_B8A8#, 16#0000_0000_AB7A_FF2A#);
   V12_K_Pair : aliased constant V12_Key :=
     (16#0000_0000_F20C_0DFE#, 16#0000_0000_493C_7D27#);
   V12_K_Four : aliased constant V12_Key :=
     (16#0000_0000_3DA6_D0CB#, 16#0000_0000_BA4F_C28E#);
   V12_K_Final : aliased constant V12_Key :=
     (16#0000_0000_740E_EF02#, 16#0000_0000_9E4A_DDF8#);

   function Update_1024_V12
     (State : U32;
      Data  : Byte_Array) return U32 is
      Pointer : System.Address := Data (Data'First)'Address;
      Result  : U32;
   begin
      --  Fixed registers follow the pinned Rust v12e_v1 allocation and are
      --  all caller-saved under AAPCS64.  The exact length makes the entire
      --  operation one region: no accumulator crosses the asm boundary and
      --  arbitrary input alignment remains valid for AArch64 LDP.
      Asm
        (Template =>
           "ldp q19, q17, [%x1]" & ASCII.LF & ASCII.HT &
           "ldp q18, q2, [%x1, #32]" & ASCII.LF & ASCII.HT &
           "ldp q16, q6, [%x1, #64]" & ASCII.LF & ASCII.HT &
           "ldp q7, q1, [%x1, #96]" & ASCII.LF & ASCII.HT &
           "ldp q5, q3, [%x1, #128]" & ASCII.LF & ASCII.HT &
           "ldp q4, q0, [%x1, #160]" & ASCII.LF & ASCII.HT &
           "movi v20.2d, #0" & ASCII.LF & ASCII.HT &
           "ins v20.s[0], %w2" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v19.16b, v20.16b" & ASCII.LF & ASCII.HT &
           "ldr q20, [%x3]" & ASCII.LF & ASCII.HT &
           "add %x1, %x1, #192" & ASCII.LF & ASCII.HT &
           "mov x9, #4" & ASCII.LF & ASCII.HT &
           "1:" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v19.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "ldp q23, q24, [%x1]" & ASCII.LF & ASCII.HT &
           "eor3 v19.16b, v23.16b, v22.16b, v19.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v17.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v17.1q, v17.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v17.16b, v24.16b, v22.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v18.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v18.1q, v18.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "ldp q23, q24, [%x1, #32]" & ASCII.LF & ASCII.HT &
           "eor3 v18.16b, v23.16b, v22.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v2.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v2.1q, v2.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v2.16b, v24.16b, v22.16b, v2.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v16.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v16.1q, v16.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "ldp q23, q24, [%x1, #64]" & ASCII.LF & ASCII.HT &
           "eor3 v16.16b, v23.16b, v22.16b, v16.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v6.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v6.1q, v6.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v6.16b, v24.16b, v22.16b, v6.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v7.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v7.1q, v7.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "ldp q23, q24, [%x1, #96]" & ASCII.LF & ASCII.HT &
           "eor3 v7.16b, v23.16b, v22.16b, v7.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v1.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v1.1q, v1.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v1.16b, v24.16b, v22.16b, v1.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v5.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v5.1q, v5.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "ldp q23, q24, [%x1, #128]" & ASCII.LF & ASCII.HT &
           "eor3 v5.16b, v23.16b, v22.16b, v5.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v3.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v3.1q, v3.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v3.16b, v24.16b, v22.16b, v3.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v4.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v4.1q, v4.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "ldp q23, q24, [%x1, #160]" & ASCII.LF & ASCII.HT &
           "eor3 v4.16b, v23.16b, v22.16b, v4.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v0.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v0.1q, v0.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v0.16b, v24.16b, v22.16b, v0.16b" & ASCII.LF & ASCII.HT &
           "add %x1, %x1, #192" & ASCII.LF & ASCII.HT &
           "subs x9, x9, #1" & ASCII.LF & ASCII.HT &
           "b.ne 1b" & ASCII.LF & ASCII.HT &
           "ldr q20, [%x4]" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v19.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v19.16b, v19.16b, v22.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v18.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v18.1q, v18.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v18.16b, v18.16b, v22.16b, v2.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v16.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v16.1q, v16.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v16.16b, v16.16b, v22.16b, v6.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v7.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v7.1q, v7.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v7.16b, v7.16b, v22.16b, v1.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v5.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v5.1q, v5.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v5.16b, v5.16b, v22.16b, v3.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v4.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v4.1q, v4.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v4.16b, v4.16b, v22.16b, v0.16b" & ASCII.LF & ASCII.HT &
           "ldr q20, [%x5]" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v19.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v19.16b, v19.16b, v22.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v16.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v16.1q, v16.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v16.16b, v16.16b, v22.16b, v7.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v5.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v5.1q, v5.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v5.16b, v5.16b, v22.16b, v4.16b" & ASCII.LF & ASCII.HT &
           "ldr q20, [%x6]" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v19.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v19.16b, v19.16b, v22.16b, v16.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v19.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v19.16b, v19.16b, v22.16b, v5.16b" & ASCII.LF & ASCII.HT &
           "umov x9, v19.d[0]" & ASCII.LF & ASCII.HT &
           "umov x10, v19.d[1]" & ASCII.LF & ASCII.HT &
           "crc32cx %w0, wzr, x9" & ASCII.LF & ASCII.HT &
           "crc32cx %w0, %w0, x10" & ASCII.LF & ASCII.HT &
           "movi v20.2d, #0" & ASCII.LF & ASCII.HT &
           "ins v20.s[0], %w0" & ASCII.LF & ASCII.HT &
           "ldp q19, q17, [%x1]" & ASCII.LF & ASCII.HT &
           "eor v19.16b, v19.16b, v20.16b" & ASCII.LF & ASCII.HT &
           "ldr q20, [%x4]" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v19.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v19.16b, v19.16b, v22.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "ldp q17, q18, [%x1, #32]" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v19.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v19.16b, v19.16b, v22.16b, v17.16b" & ASCII.LF & ASCII.HT &
           "pmull v22.1q, v19.1d, v20.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v19.1q, v19.2d, v20.2d" & ASCII.LF & ASCII.HT &
           "eor3 v19.16b, v19.16b, v22.16b, v18.16b" & ASCII.LF & ASCII.HT &
           "umov x9, v19.d[0]" & ASCII.LF & ASCII.HT &
           "umov x10, v19.d[1]" & ASCII.LF & ASCII.HT &
           "crc32cx %w0, wzr, x9" & ASCII.LF & ASCII.HT &
           "crc32cx %w0, %w0, x10",
         Outputs =>
           [U32'Asm_Output ("=&r", Result),
            System.Address'Asm_Output ("+&r", Pointer)],
         Inputs   =>
           [U32'Asm_Input ("r", State),
            System.Address'Asm_Input ("r", V12_K_Fold_12'Address),
            System.Address'Asm_Input ("r", V12_K_Pair'Address),
            System.Address'Asm_Input ("r", V12_K_Four'Address),
            System.Address'Asm_Input ("r", V12_K_Final'Address)],
         Clobber  =>
           "cc,memory,x9,x10," &
           "v0,v1,v2,v3,v4,v5,v6,v7,v16,v17,v18,v19,v20,v22,v23,v24",
         Volatile => True);
      return Result;
   end Update_1024_V12;

   function Next
     (Source : System.Address;
      Bytes  : Count) return System.Address is
     (System.Storage_Elements."+"
        (Source, System.Storage_Elements.Storage_Offset (Bytes)));
   pragma Inline_Always (Next);

   function Alignment
     (Source : System.Address;
      Bytes  : Count) return Count is
     (Count
        (System.Storage_Elements."mod"
           (Source, System.Storage_Elements.Storage_Offset (Bytes))));
   pragma Inline_Always (Alignment);

   function Load_Byte (Source : System.Address) return U32 is
      Item : U8 with Import, Address => Source;
   begin
      return U32 (Item);
   end Load_Byte;
   pragma Inline_Always (Load_Byte);

   function Load_64 (Source : System.Address) return U64 is
      Item : U64 with Import, Address => Source;
   begin
      return Item;
   end Load_64;
   pragma Inline_Always (Load_64);

   function Load_128 (Source : System.Address) return Vector is
      Bytes  : Byte_Block with Import, Address => Source;
      Result : Vector;
   begin
      Asm
        (Template => "ldr %q0, %1",
         Outputs  => Vector'Asm_Output ("=&w", Result),
         Inputs   => Byte_Block'Asm_Input ("Q", Bytes));
      return Result;
   end Load_128;
   pragma Inline_Always (Load_128);

   function Pair (Low, High : U64) return Vector is
      Result : Vector;
   begin
      Asm
        (Template =>
           "movi %0.2d, #0" & ASCII.LF & ASCII.HT &
           "ins %0.d[0], %x1" & ASCII.LF & ASCII.HT &
           "ins %0.d[1], %x2",
         Outputs => Vector'Asm_Output ("=&w", Result),
         Inputs  =>
           [U64'Asm_Input ("r", Low),
            U64'Asm_Input ("r", High)]);
      return Result;
   end Pair;
   pragma Inline_Always (Pair);

   function Low_Lane (Item : Vector) return U64 is
      Result : U64;
   begin
      Asm
        (Template => "umov %x0, %1.d[0]",
         Outputs  => U64'Asm_Output ("=r", Result),
         Inputs   => Vector'Asm_Input ("w", Item));
      return Result;
   end Low_Lane;
   pragma Inline_Always (Low_Lane);

   function High_Lane (Item : Vector) return U64 is
      Result : U64;
   begin
      Asm
        (Template => "umov %x0, %1.d[1]",
         Outputs  => U64'Asm_Output ("=r", Result),
         Inputs   => Vector'Asm_Input ("w", Item));
      return Result;
   end High_Lane;
   pragma Inline_Always (High_Lane);

   function Xor_128 (Left, Right : Vector) return Vector is
      Result : Vector;
   begin
      Asm
        (Template => "eor %0.16b, %1.16b, %2.16b",
         Outputs  => Vector'Asm_Output ("=&w", Result),
         Inputs   =>
           [Vector'Asm_Input ("w", Left),
            Vector'Asm_Input ("w", Right)]);
      return Result;
   end Xor_128;
   pragma Inline_Always (Xor_128);

   function EOR3 (First, Second, Third : Vector) return Vector is
      Result : Vector;
   begin
      Asm
        (Template => "eor3 %0.16b, %1.16b, %2.16b, %3.16b",
         Outputs  => Vector'Asm_Output ("=&w", Result),
         Inputs   =>
           [Vector'Asm_Input ("w", First),
            Vector'Asm_Input ("w", Second),
            Vector'Asm_Input ("w", Third)]);
      return Result;
   end EOR3;
   pragma Inline_Always (EOR3);

   procedure Fold_EOR3
     (Current     : in out Vector;
      Coefficient : Vector;
      Data        : Vector) is
      Low_Product : Vector;
   begin
      Asm
        (Template =>
           "pmull %1.1q, %0.1d, %2.1d" & ASCII.LF & ASCII.HT &
           "pmull2 %0.1q, %0.2d, %2.2d" & ASCII.LF & ASCII.HT &
           "eor3 %0.16b, %0.16b, %1.16b, %3.16b",
         Outputs =>
           [Vector'Asm_Output ("+&w", Current),
            Vector'Asm_Output ("=&w", Low_Product)],
         Inputs  =>
           [Vector'Asm_Input ("w", Coefficient),
            Vector'Asm_Input ("w", Data)]);
   end Fold_EOR3;
   pragma Inline_Always (Fold_EOR3);

   procedure Fold_192_Loop
     (Vector_Ptr  : in out System.Address;
      Stream0_Ptr : in out System.Address;
      Stream1_Ptr : in out System.Address;
      Stream2_Ptr : in out System.Address;
      Iterations  : in out Count;
      CRC0        : in out U32;
      CRC1        : in out U32;
      CRC2        : in out U32;
      K           : Vector;
      X           : in out Accumulator_Array) is
   begin
      --  Keep the nine fold accumulators and all three scalar CRC streams in
      --  registers for the complete pinned 192-byte loop.  The post-indexed
      --  loads are its exact 9-vector/6-word input geometry.
      --
      --  Fixed registers are deliberate: GNAT otherwise emits copy-in/out
      --  MOVs for each loop-carried vector asm operand.  v0 .. v8 hold the
      --  accumulators, v9 .. v11 are data/product scratch, v12 holds the key,
      --  and x9 .. x14 hold the six CRC words.  The clobber list leaves ABI
      --  preservation to the compiler; accumulator memory traffic stays
      --  outside the repeated label.
      Asm
        (Template =>
           "ldp q0, q1, [%x0, #-144]" & ASCII.LF & ASCII.HT &
           "ldp q2, q3, [%x0, #-112]" & ASCII.LF & ASCII.HT &
           "ldp q4, q5, [%x0, #-80]" & ASCII.LF & ASCII.HT &
           "ldp q6, q7, [%x0, #-48]" & ASCII.LF & ASCII.HT &
           "ldr q8, [%x0, #-16]" & ASCII.LF & ASCII.HT &
           "ldr q12, [%x9]" & ASCII.LF & ASCII.HT &
           "1:" & ASCII.LF & ASCII.HT &
           "ldp q9, q10, [%x0], #32" & ASCII.LF & ASCII.HT &
           "pmull v11.1q, v0.1d, v12.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v0.1q, v0.2d, v12.2d" & ASCII.LF & ASCII.HT &
           "eor3 v0.16b, v0.16b, v11.16b, v9.16b" & ASCII.LF & ASCII.HT &
           "pmull v11.1q, v1.1d, v12.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v1.1q, v1.2d, v12.2d" & ASCII.LF & ASCII.HT &
           "eor3 v1.16b, v1.16b, v11.16b, v10.16b" & ASCII.LF & ASCII.HT &
           "ldp q9, q10, [%x0], #32" & ASCII.LF & ASCII.HT &
           "pmull v11.1q, v2.1d, v12.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v2.1q, v2.2d, v12.2d" & ASCII.LF & ASCII.HT &
           "eor3 v2.16b, v2.16b, v11.16b, v9.16b" & ASCII.LF & ASCII.HT &
           "pmull v11.1q, v3.1d, v12.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v3.1q, v3.2d, v12.2d" & ASCII.LF & ASCII.HT &
           "eor3 v3.16b, v3.16b, v11.16b, v10.16b" & ASCII.LF & ASCII.HT &
           "ldp q9, q10, [%x0], #32" & ASCII.LF & ASCII.HT &
           "pmull v11.1q, v4.1d, v12.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v4.1q, v4.2d, v12.2d" & ASCII.LF & ASCII.HT &
           "eor3 v4.16b, v4.16b, v11.16b, v9.16b" & ASCII.LF & ASCII.HT &
           "pmull v11.1q, v5.1d, v12.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v5.1q, v5.2d, v12.2d" & ASCII.LF & ASCII.HT &
           "eor3 v5.16b, v5.16b, v11.16b, v10.16b" & ASCII.LF & ASCII.HT &
           "ldp q9, q10, [%x0], #32" & ASCII.LF & ASCII.HT &
           "pmull v11.1q, v6.1d, v12.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v6.1q, v6.2d, v12.2d" & ASCII.LF & ASCII.HT &
           "eor3 v6.16b, v6.16b, v11.16b, v9.16b" & ASCII.LF & ASCII.HT &
           "pmull v11.1q, v7.1d, v12.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v7.1q, v7.2d, v12.2d" & ASCII.LF & ASCII.HT &
           "eor3 v7.16b, v7.16b, v11.16b, v10.16b" & ASCII.LF & ASCII.HT &
           "ldr q9, [%x0], #16" & ASCII.LF & ASCII.HT &
           "pmull v11.1q, v8.1d, v12.1d" & ASCII.LF & ASCII.HT &
           "pmull2 v8.1q, v8.2d, v12.2d" & ASCII.LF & ASCII.HT &
           "eor3 v8.16b, v8.16b, v11.16b, v9.16b" & ASCII.LF & ASCII.HT &
           "ldp x9, x10, [%x1], #16" & ASCII.LF & ASCII.HT &
           "ldp x11, x12, [%x2], #16" & ASCII.LF & ASCII.HT &
           "ldp x13, x14, [%x3], #16" & ASCII.LF & ASCII.HT &
           "crc32cx %w5, %w5, x9" & ASCII.LF & ASCII.HT &
           "crc32cx %w6, %w6, x11" & ASCII.LF & ASCII.HT &
           "crc32cx %w7, %w7, x13" & ASCII.LF & ASCII.HT &
           "crc32cx %w5, %w5, x10" & ASCII.LF & ASCII.HT &
           "crc32cx %w6, %w6, x12" & ASCII.LF & ASCII.HT &
           "crc32cx %w7, %w7, x14" & ASCII.LF & ASCII.HT &
           "subs %x4, %x4, #1" & ASCII.LF & ASCII.HT &
           "b.ne 1b" & ASCII.LF & ASCII.HT &
           "stp q0, q1, [%x8]" & ASCII.LF & ASCII.HT &
           "stp q2, q3, [%x8, #32]" & ASCII.LF & ASCII.HT &
           "stp q4, q5, [%x8, #64]" & ASCII.LF & ASCII.HT &
           "stp q6, q7, [%x8, #96]" & ASCII.LF & ASCII.HT &
           "str q8, [%x8, #128]",
         Outputs =>
           [System.Address'Asm_Output ("+&r", Vector_Ptr),
            System.Address'Asm_Output ("+&r", Stream0_Ptr),
            System.Address'Asm_Output ("+&r", Stream1_Ptr),
            System.Address'Asm_Output ("+&r", Stream2_Ptr),
            Count'Asm_Output ("+&r", Iterations),
            U32'Asm_Output ("+&r", CRC0),
            U32'Asm_Output ("+&r", CRC1),
            U32'Asm_Output ("+&r", CRC2)],
         Inputs   =>
           [System.Address'Asm_Input ("r", X'Address),
            System.Address'Asm_Input ("r", K'Address)],
         Clobber  =>
           "cc,memory,x9,x10,x11,x12,x13,x14," &
           "v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12",
         Volatile => True);
   end Fold_192_Loop;
   pragma Inline_Always (Fold_192_Loop);

   function CLMUL_Scalar (Left, Right : U32) return Vector is
      Result : Vector;
      A      : Vector;
      B      : Vector;
   begin
      Asm
        (Template =>
           "movi %1.2d, #0" & ASCII.LF & ASCII.HT &
           "movi %2.2d, #0" & ASCII.LF & ASCII.HT &
           "ins %1.s[0], %w3" & ASCII.LF & ASCII.HT &
           "ins %2.s[0], %w4" & ASCII.LF & ASCII.HT &
           "pmull %0.1q, %1.1d, %2.1d",
         Outputs =>
           [Vector'Asm_Output ("=&w", Result),
            Vector'Asm_Output ("=&w", A),
            Vector'Asm_Output ("=&w", B)],
         Inputs  =>
           [U32'Asm_Input ("r", Left),
            U32'Asm_Input ("r", Right)]);
      return Result;
   end CLMUL_Scalar;
   pragma Inline_Always (CLMUL_Scalar);

   function Packed_Byte_Square (Item : U32) return U64 is
      Result  : U64;
      Input   : Vector;
      Squared : Vector;
   begin
      --  VMULL.P8 squares the eight polynomial bytes independently. Item
      --  occupies the first four bytes, so the low
      --  64-bit result is exactly the carry-less square of the 32-bit Item.
      Asm
        (Template =>
           "movi %1.2d, #0" & ASCII.LF & ASCII.HT &
           "ins %1.s[0], %w3" & ASCII.LF & ASCII.HT &
           "pmull %2.8h, %1.8b, %1.8b" & ASCII.LF & ASCII.HT &
           "umov %x0, %2.d[0]",
         Outputs =>
           [U64'Asm_Output ("=r", Result),
            Vector'Asm_Output ("=&w", Input),
            Vector'Asm_Output ("=&w", Squared)],
         Inputs  => U32'Asm_Input ("r", Item));
      return Result;
   end Packed_Byte_Square;
   pragma Inline_Always (Packed_Byte_Square);

   function CRC32C_Byte (CRC, Item : U32) return U32 is
      Result : U32;
   begin
      Asm
        (Template => "crc32cb %w0, %w1, %w2",
         Outputs  => U32'Asm_Output ("=r", Result),
         Inputs   =>
           [U32'Asm_Input ("r", CRC),
            U32'Asm_Input ("r", Item)]);
      return Result;
   end CRC32C_Byte;
   pragma Inline_Always (CRC32C_Byte);

   function CRC32C_32 (CRC, Item : U32) return U32 is
      Result : U32;
   begin
      Asm
        (Template => "crc32cw %w0, %w1, %w2",
         Outputs  => U32'Asm_Output ("=r", Result),
         Inputs   =>
           [U32'Asm_Input ("r", CRC),
            U32'Asm_Input ("r", Item)]);
      return Result;
   end CRC32C_32;
   pragma Inline_Always (CRC32C_32);

   function CRC32C_64 (CRC : U32; Item : U64) return U32 is
      Result : U32;
   begin
      Asm
        (Template => "crc32cx %w0, %w1, %x2",
         Outputs  => U32'Asm_Output ("=r", Result),
         Inputs   =>
           [U32'Asm_Input ("r", CRC),
            U64'Asm_Input ("r", Item)]);
      return Result;
   end CRC32C_64;
   pragma Inline_Always (CRC32C_64);

   function XNModP (Exponent : U64) return U32 is
      N       : U64 := Exponent;
      Stack   : U64 := not U64 (1);
      Acc     : U32;
      Low_Bit : U32;
   begin
      while N > 191 loop
         Stack := Interfaces.Shift_Left (Stack, 1) + (N and 1);
         N := Interfaces.Shift_Right (N, 1) - 16;
      end loop;
      Stack := not Stack;
      Acc := Interfaces.Shift_Right (16#8000_0000#, Natural (N and 31));
      N := Interfaces.Shift_Right (N, 5);

      while N > 0 loop
         Acc := CRC32C_32 (Acc, 0);
         N := N - 1;
      end loop;

      loop
         Low_Bit := U32 (Stack and 1);
         Stack := Interfaces.Shift_Right (Stack, 1);
         exit when Stack = 0;
         Acc :=
           CRC32C_64
             (0,
              Interfaces.Shift_Left
                (Packed_Byte_Square (Acc), Natural (Low_Bit)));
      end loop;
      return Acc;
   end XNModP;
   pragma Inline_Always (XNModP);

   function CRC_Shift (CRC : U32; Byte_Length : Count) return Vector is
      Exponent : constant U64 := U64 (Byte_Length) * 8 - 33;
   begin
      return CLMUL_Scalar (CRC, XNModP (Exponent));
   end CRC_Shift;
   pragma Inline_Always (CRC_Shift);

   function Update
     (State : U32;
      Data  : Byte_Array) return U32 is
      CRC0       : U32 := State;
      CRC1       : U32 := 0;
      CRC2       : U32 := 0;
      Pointer    : System.Address := Data'Address;
      Vector_Ptr : System.Address;
      Initial_Vector_Ptr : System.Address;
      Stream1_Ptr : System.Address;
      Stream2_Ptr : System.Address;
      Remaining  : Count := Count (Data'Length);
      Blocks     : Count;
      Iterations : Count;
      KLen       : Count;
      K          : Vector;
      VC0        : Vector;
      VC1        : Vector;
      VC2        : Vector;
      VC         : U64;
      X          : Accumulator_Array;
   begin
      if Remaining = 0 then
         return CRC0;
      end if;

      while Remaining > 0 and then Alignment (Pointer, 8) /= 0 loop
         CRC0 := CRC32C_Byte (CRC0, Load_Byte (Pointer));
         Pointer := Next (Pointer, 1);
         Remaining := Remaining - 1;
      end loop;

      if Alignment (Pointer, 16) /= 0 and then Remaining >= 8 then
         CRC0 := CRC32C_64 (CRC0, Load_64 (Pointer));
         Pointer := Next (Pointer, 8);
         Remaining := Remaining - 8;
      end if;

      if Remaining >= 192 then
         Blocks := Remaining / 192;
         KLen := Blocks * 16;
         Vector_Ptr := Next (Pointer, KLen * 3);
         Initial_Vector_Ptr := Vector_Ptr;

         Vector_Ptr := Next (Vector_Ptr, 144);

         --  Exact pinned v9s3x2e_s3 nine-stream fold key pair.
         K := Pair (16#0000_0000_7E90_8048#, 16#0000_0000_C96C_FDC0#);
         Iterations := Blocks - 1;
         Stream1_Ptr := Next (Pointer, KLen);
         Stream2_Ptr := Next (Pointer, KLen * 2);
         if Iterations > 0 then
            Fold_192_Loop
              (Vector_Ptr, Pointer, Stream1_Ptr, Stream2_Ptr,
               Iterations, CRC0, CRC1, CRC2, K, X);
         else
            X (0) := Load_128 (Initial_Vector_Ptr);
            X (1) := Load_128 (Next (Initial_Vector_Ptr, 16));
            X (2) := Load_128 (Next (Initial_Vector_Ptr, 32));
            X (3) := Load_128 (Next (Initial_Vector_Ptr, 48));
            X (4) := Load_128 (Next (Initial_Vector_Ptr, 64));
            X (5) := Load_128 (Next (Initial_Vector_Ptr, 80));
            X (6) := Load_128 (Next (Initial_Vector_Ptr, 96));
            X (7) := Load_128 (Next (Initial_Vector_Ptr, 112));
            X (8) := Load_128 (Next (Initial_Vector_Ptr, 128));
         end if;

         --  Exact pinned pairwise, four-lane, and final reduction keys.
         K := Pair (16#0000_0000_F20C_0DFE#, 16#0000_0000_493C_7D27#);
         Fold_EOR3 (X (0), K, X (1));
         X (1) := X (2);
         X (2) := X (3);
         X (3) := X (4);
         X (4) := X (5);
         X (5) := X (6);
         X (6) := X (7);
         X (7) := X (8);

         Fold_EOR3 (X (0), K, X (1));
         Fold_EOR3 (X (2), K, X (3));
         Fold_EOR3 (X (4), K, X (5));
         Fold_EOR3 (X (6), K, X (7));

         K := Pair (16#0000_0000_3DA6_D0CB#, 16#0000_0000_BA4F_C28E#);
         Fold_EOR3 (X (0), K, X (2));
         Fold_EOR3 (X (4), K, X (6));

         K := Pair (16#0000_0000_740E_EF02#, 16#0000_0000_9E4A_DDF8#);
         Fold_EOR3 (X (0), K, X (4));

         CRC0 := CRC32C_64 (CRC0, Load_64 (Pointer));
         CRC1 := CRC32C_64 (CRC1, Load_64 (Next (Pointer, KLen)));
         CRC2 := CRC32C_64 (CRC2, Load_64 (Next (Pointer, KLen * 2)));
         CRC0 := CRC32C_64 (CRC0, Load_64 (Next (Pointer, 8)));
         CRC1 := CRC32C_64 (CRC1, Load_64 (Next (Pointer, KLen + 8)));
         CRC2 := CRC32C_64 (CRC2, Load_64 (Next (Pointer, KLen * 2 + 8)));

         VC0 := CRC_Shift (CRC0, KLen * 2 + Blocks * 144);
         VC1 := CRC_Shift (CRC1, KLen + Blocks * 144);
         VC2 := CRC_Shift (CRC2, Blocks * 144);
         VC := Low_Lane (EOR3 (VC0, VC1, VC2));

         CRC0 := CRC32C_64 (0, Low_Lane (X (0)));
         CRC0 := CRC32C_64 (CRC0, VC xor High_Lane (X (0)));

         Pointer := Vector_Ptr;
         Remaining := Remaining mod 192;
      end if;

      if Remaining >= 32 then
         KLen := ((Remaining - 8) / 24) * 8;
         CRC1 := 0;
         CRC2 := 0;
         loop
            CRC0 := CRC32C_64 (CRC0, Load_64 (Pointer));
            CRC1 := CRC32C_64 (CRC1, Load_64 (Next (Pointer, KLen)));
            CRC2 := CRC32C_64 (CRC2, Load_64 (Next (Pointer, KLen * 2)));
            Pointer := Next (Pointer, 8);
            Remaining := Remaining - 24;
            exit when Remaining < 32;
         end loop;

         VC0 := CRC_Shift (CRC0, KLen * 2 + 8);
         VC1 := CRC_Shift (CRC1, KLen + 8);
         VC := Low_Lane (Xor_128 (VC0, VC1));

         Pointer := Next (Pointer, KLen * 2);
         CRC0 := CRC32C_64 (CRC2, Load_64 (Pointer) xor VC);
         Pointer := Next (Pointer, 8);
         Remaining := Remaining - 8;
      end if;

      while Remaining >= 8 loop
         CRC0 := CRC32C_64 (CRC0, Load_64 (Pointer));
         Pointer := Next (Pointer, 8);
         Remaining := Remaining - 8;
      end loop;

      while Remaining > 0 loop
         CRC0 := CRC32C_Byte (CRC0, Load_Byte (Pointer));
         Pointer := Next (Pointer, 1);
         Remaining := Remaining - 1;
      end loop;

      return CRC0;
   end Update;
end Flyology_CRC.CRC32C_PMULL_EOR3_V9S3X2E_S3;
